### ISSUE TITLE
RunningStatistics Combine Method Must Always Return a New Instance

### ISSUE THREAD

**Issue by github-srj** [mathnet/mathnet-numerics#1021]
The optimization for empty instances at the beginning of the method returns a reference to one of the input instances is empty (count=0).
When RunningStatistics instance(s) are contained in another class, unintended modifications can occur when the instance subsequently modified by any referencing container.
The resulting problems may be difficult to locate / diagnose.
 
A trivial clone constructor (preferably public) would facilitate easy remediation.
The Clone constructor can then be used by the optimization in the Combine method to resolve issue.

**Comment by cdrnet** [comment]
Yes, I see where you're coming from. A nice example of why I like Rust so much (over C#), where this problem could not appear at all, by design. I also agree with your proposed remediation, let's change it this way.
