### ISSUE TITLE
Signed Edition issue with MathNet.Numerics.FSharp, MathNet.Numerics.Data and MathNet.Numerics.Native

### ISSUE THREAD

**Issue by tibel** [mathnet/mathnet-numerics#140]
At the moment it is not possible to use MathNet.Numerics.FSharp or MathNet.Numerics.Data from a strong-named assembly. Same is true for using the native providers as the nuget package depends on the unsigned version.

I think there should only be one version of the library and this should be the signed version. Nuget now supports adding version redirect rules to App.Config to deal with versioning issues.

So rethink your decision with signed and unsigned edition, please.

**Comment by cdrnet** [comment]
Picking this up again. There is a weak and unverified reason regarding MKL licensing when offering the MKL binaries independently, as we're only allowed to ship them as part of Math.NET Numerics (to my understanding). But given that it is actually statically compiled into the MathNet.Numerics.MKL.dll this is actually the case, so it should be possible to drop the package dependency. This was blocking not only in the -signed scenario but was also inconvenient when trying to control the native provider of choice from application level, see #312.
