### ISSUE TITLE
Restore ACML and GotoBLAS2/LAPACK native providers

### ISSUE THREAD

**Issue by cdrnet** [mathnet/mathnet-numerics#143]
From: https://mathnetnumerics.codeplex.com/workitem/5720
and: https://mathnetnumerics.codeplex.com/workitem/5678

> Algorithms.LinearAlgebra.Acml namespace as well as several others - apart from MKL have disappeared in the latest version. 
> This means that native wrapper tests no longer build. 
> In general I must say that it is horrendously complicated to enable any non-managed BLAS engine. 
> It would be really nice if default download included at least one non-managed BLAS implementation - e.g. the reference one. As it stands, one has to spend huge amount of time obtaining pieces of software from various sources. 
> It also means that default (managed) implementation is several factors of magnitude slower than Matlab, R or the like when it comes to manipulating sizeable matrices.

**Comment by tibel** [comment]
As OpenBLAS is now supported there is no need for GotoBLAS2.
So ACML provider is missing only.
