### ISSUE TITLE
ANOVA and MANOVA support

### ISSUE THREAD

**Issue by cdrnet** [mathnet/mathnet-numerics#154]
From: https://mathnetnumerics.codeplex.com/workitem/5704

> I am looking to implement a multivariant ANOVA (MANOVA) with some help (I am not a Statistician, just a Biologist who plays one ;D ). Can we add this to Math.NET easily? And if so what are the rules for code creation, et al. that I need to follow? Also I will probably implement One and 2 Way ANOVAS also (they should be easier).

**Comment by serialkiller** [comment]
Any update on this feature ? It would be really helpful to get it.

**Comment by Fabian3223** [comment]
Any update? It would be very useful

**Comment by cdrnet** [comment]
Unfortunately I'm not aware of anyone actively working on this at the moment.
