### ISSUE TITLE
Support for arbitrarily large integers (ie. Matrix of BigInteger)

### ISSUE THREAD

**Issue by Superbest** [mathnet/mathnet-numerics#190]
Is support for a matrix made up of BigInteger planned?

If it is not planned, it should be. If it already exists, it needs to be documented more explicitly.

**Comment by MaLiN2223** [comment]
How about creating matrix for generic type? I did it [here](https://github.com/MaLiN2223/Malins/blob/master/C%23/DataStructures/Matrices/Generics/Matrix.cs) and I think it might be usefull because creating class Matrix : Matrix<type> for every type might be exhausting.

**Comment by MovGP0** [comment]
there should be support for arbitrary large floating-point-decimals too. we could use [the W3b.Sine library](https://github.com/vogon/Demotic/tree/master/W3b.Sine) which provides the elementary math functions.
