### ISSUE TITLE
Bug reading in an empty cell as zero from a CSV file using DelimitedReader

### ISSUE THREAD

**Issue by camazotz** [mathnet/mathnet-numerics#241]
I'm using DelimitedReader to read a CSV file and I noticed that whenever there was an empty cell in the CSV file, the 'zero' would either not appear at all, or be inserted at the end of the row.

So if I try to read the following sequence of numbers,

6, [empty], 2, 4, 4, 3

Then my output matrix has them in this order:

6, 2, 4, 4, 3

There is no zero.

If I try to read in this sequence of numbers:

6, [empty], 2, 4, 4, 3
2, 0, 3, 8, 7, 6
1, 3, 1, 5, 7, 8

Then my output matrix has them in this order:

6, 2, 4, 4, 3, 0
2, 0, 3, 8, 7, 6
1, 3, 1, 5, 7, 8

So in this case, a 'zero' was appended to the end of the row.
I'm using the following code to read in the CSV file to the matrix:
Matrix<double> matrix = DelimitedReader.Read<double>("test.csv", true, ",", false);

And I'm reading out the values in the matrix through this code:
for (int i = 0; i < matrix.RowCount; i++)
            {
                for (int j = 0; j < matrix.ColumnCount; j++)
                {
                    Console.WriteLine(matrix[i, j]);
                }
            }

Thanks so much for looking into this!

**Comment by cuda** [comment]
tinkered a little with this: https://github.com/cuda/mathnet-numerics/tree/csv

**Comment by cuda** [comment]
no, this is a mess. I still cannot easily match a case where we only have missing values, such as ',,,,'. Maybe we need a second delimited reader that uses a full parser instead of a regex expression. Slower but would handle missing data better.

**Comment by cuda** [comment]
pushed one more try. I think it now handles all the different permutations of an empty row. I'll benchmark to see much slower it is.

**Comment by cuda** [comment]
ouch, 40% slower

**Comment by cuda** [comment]
latest push gets it down to 15% slower.

**Comment by cdrnet** [comment]
Well, some minor slow down is expected and acceptable if it buys us correctness. Thanks for looking into this!

**Comment by cuda** [comment]
Did some more testing and it seems to work well. Also added missing value support to the delimited writer.

**Comment by cdrnet** [comment]
Closing since fixed in master - thanks again!
