### ISSUE TITLE
One MKL package containing x86 and x64

### ISSUE THREAD

**Issue by tibel** [mathnet/mathnet-numerics#269]
As you have written quite some time ago (http://christoph.ruegg.name/blog/loading-native-dlls-in-fsharp-interactive.html):
it would be great to have one native provider package and at runtime the correct architecture (x64/x84) version is used.

I think System.Data.SQLite has implemented some solution for this already.

**Comment by tibel** [comment]
Targets file for nuget package: https://gist.github.com/tibel/f307bce65b08cfdba833

**Comment by cdrnet** [comment]
Great, thanks! I'll prepare a new releases for the new MKL 11.2 Update 3 and will include this in a new combined package.

**Comment by cdrnet** [comment]
Implemented in the build (Windows package only for now) and verified to work well in a first test.
