### ISSUE TITLE
Appending matrix and vector 

### ISSUE THREAD

**Issue by forki** [mathnet/mathnet-numerics#277]
In octave we can write:

    X = [ones(m, 1), data(:,1)]; % Add a column of ones to x

this is what I have with Mathnet:

    let ones m n = DenseMatrix.init m n (fun i j -> 1.)
    let A = loadCSV "ex1data1.txt" |> allFloats // returns 97x2 DenseMatrix
    let X = (ones A.RowCount 1).Append(A.RemoveColumn(1))

Is there a way to append vector to a matrix? I cheated a bit and removed the second column instead selecting the first. This keeps the type as Matrix.

Ideally I'd like to write something that looks more like Octave ;-)

**Comment by cdrnet** [comment]
You can append, prepend or insert a vector to a matrix using the InsertRow or InsertColumn methods. They expect an index and a vector. Math.NET Numerics has the concept of vectors which do not have an orientation (as opposed to a single-column/row matrix)

From the octave viewpoint:

* `data(:,1)` becomes `data.[*,0]` using the F# slice syntax and zero-based indexing (octave is 1-based if I remember correctly)

* `[a,b]` becomes `DenseMatrix.ofColumns [a; b]` if a and b are vectors. `Append` or `ofMatrixArray2` can be used when a and b are matrices.

* `ones` can also be written as `let ones m n = DenseMatrix.create m n 1.`

So you could write X as:

    DenseMatrix.ofColumns [DenseVector.create data.RowCount 1.0; data.[*,0]]

**Comment by forki** [comment]
cool that's a bit nicer.

Now I need to go one step further: 
Consider A a 27x3 matrix, the the following works:

  DenseMatrix.ofColumns [DenseVector.create A.RowCount 1.0; A.[*,0] ; A.[*,1]]

But in general I want to append all columns from A but the last one.
This possible?

**Comment by cdrnet** [comment]
Something along the line of the following?

    DenseMatrix.ofColumns [DenseVector.create A.RowCount 1.0; A.RemoveColumn(A.ColumnCount-1)]

**Comment by cdrnet** [comment]
We could indeed do with some more F# shortcut functions

**Comment by forki** [comment]
let X = DenseMatrix.ofColumns [DenseVector.create A.RowCount 1.0; A.RemoveColumn(A.ColumnCount-1)]
    error FS0001: The type 'Matrix<float>' is not compatible with the type 'Vector<float>'

that's the error I had at the beginning there seems to be no way to mix and match vectors and matrices

**Comment by cdrnet** [comment]
Ah yes indeed. The following is even worse than your first version:

    DenseMatrix.ofMatrixArray2 (array2D [[ ones A.RowCount 1; A.[*,0..A.ColumnCount-2] ]])

Maybe we could add `DenseMatrix.append` and `DenseMatrix.stack` functions accepting a list of matrices each.

**Comment by cdrnet** [comment]
Would be nice if the `A.[*,-1]` syntax would work for slices.

**Comment by cdrnet** [comment]
Also would become a bit nicer if we added negative indexing support, where `A.[*,0..A.ColumnCount-2]` could be written as `A.[*,0..-2]` (or something like this)

**Comment by cdrnet** [comment]
With the proposed change in d8ba674 we can now write this as:

    DenseMatrix.append [ ones A.RowCount 1; A.[*, 0..A.ColumnCount-2] ]

**Comment by cdrnet** [comment]
Note that we won't be able to directly append a list of mixed matrices and vectors since our vectors have no orientation. But it will work with 1xn and mx1 matrices of course.

**Comment by forki** [comment]
appendRow and appendColumn could do the trick

**Comment by cdrnet** [comment]
Essentially the following?

    let appendRow (m:Matrix<_>) v = m.InsertRow(m.RowCount, v)
    let appendColumn (m:Matrix<_>) v = m.InsertColuimn(m.ColumnCount, v)

Yes, we could add that to the F# modules. Maybe also prepend to insert at 0-index. And insert itself.

**Comment by cdrnet** [comment]
Btw, `DenseMatrix.ofColumns` is also related to this

**Comment by forki** [comment]
yep that looks good

**Comment by cdrnet** [comment]
Added, but I've switched the argument order to work better with partial applications.

**Comment by forki** [comment]
Awesome

**Comment by cdrnet** [comment]
Release in v3.5.0.
