### ISSUE TITLE
Fourier.BluesteinForward gets "noisy" on samples larger than 46000, fails test

### ISSUE THREAD

**Issue by porsove** [mathnet/mathnet-numerics#286]
The following test code is from MatchingNaiveTransformTest.cs
        
        [Test, Explicit("Long-Running")]
        public void AlgorithmsMatchNaive_Arbitrary_Large()
        {
            // 30870 = 2*3*3*5*7*7*7
            const FourierOptions options = FourierOptions.NoScaling;
			// var samples = Generate.RandomComplex(30870, GetUniform(1)); /*PASSED*/
			var samples = Generate.RandomComplex(46500, GetUniform(1)); /*FAILED*/	
			var naive = Fourier.NaiveForward(samples, options);

            Verify(samples, 10, options, (a, b) => naive, Fourier.BluesteinForward);
        }
*********Test report:*********
Not equal within 10 places. 
Expected:(-196.017004403339, 164.486355594928); 
Actual:(-196.910997467055, 165.687716433139)

**Comment by SleuthEye** [comment]
As also noted in [this answer to a similar problem on stackoverflow](http://stackoverflow.com/a/29801128/2994596), this is a limitation of the BluesteinSequence generation for input size greater than 46341. More specifically the expression `(k*k)` within the loop exceeds the maximum representable value of the signed 32-bit `int` type used for the computation when `k` is greater than 46430.

One possible fix would be to change the type of the variable `k` to use `long` (a 64-bit type) which would extend the range to sqrt(9,223,372,036,854,775,807) ~ 3,037,000,499 before reaching the limitation (at which point the use of `double` in the algorithm would be a more dominant source of numerical error). To avoid the performance cost for smaller sized array, this extended range version could be called only for arrays with more than 46431 elements.

**Comment by cdrnet** [comment]
Thanks for this analysis!

**Comment by cdrnet** [comment]
Fixed in master, to be released in v3.7.0.
