### ISSUE TITLE
Fake build error on Ubuntu and OS X

### ISSUE THREAD

**Issue by cuda** [mathnet/mathnet-numerics#293]
"build.cmd build" works fine on Windows, but "./build.sh build" fails on Ubuntu 14.04 and OS X 10.10.2 with mono 3.12:
Status:        Failure
  ----
  1) Building /home/marcus/src/mathnet-numerics/MathNet.Numerics.sln failed with exitcode 1.
  2) : /home/marcus/src/mathnet-numerics/src/FSharp/FSharp.fsproj(0,0): Target named 'Rebuild' not found in the project.

Any ideas?

Thanks,
Marcus

**Comment by cdrnet** [comment]
No, I have not seen this yet. We use Mono 3.12 on Travis as well with exactly the same build arguments, e.g. [build 171](https://travis-ci.org/mathnet/mathnet-numerics/builds/52045196).

**Comment by cuda** [comment]
The travis log was helpful! I got it to build on ubuntu once F# was in /usr/lib/cli/fsharp . still tinker with OS X. 
Thanks

**Comment by cuda** [comment]
for OSX, don't install mono with brew if you have xamarin studio installed :)
