### ISSUE TITLE
DenseMatrix.OfRowVectors cannot handle empty sequence

### ISSUE THREAD

**Issue by NightElfik** [mathnet/mathnet-numerics#294]
`DenseMatrix.OfRowVectors(x)` where `x` is `IEnumerable` and is empty (count == 0) throws `System.IndexOutOfRangeException`.

This is most likely caused by code in `DenseColumnMajorMatrixStorage<T>.OfRowVectors(...)` which starts by following code:

```
int rows = data.Length;
int columns = data[0].Length;
var array = new T[rows*columns];
```

The `data[0]` is probably causing the exception since it has no index `0`.

**Comment by cdrnet** [comment]
We do not support matrices with zero columns or rows, so this case is expected to fail. But the actual exception is unhelpful and should be replaced with an `ArgumentException`, so I'll keep this issue open until fixed.

**Comment by cdrnet** [comment]
Fixed in master - it will now throw and `ArgumentOutOfRange` exception with a message saying that matrices cannot be empty.
