### ISSUE TITLE
MathNet.Numerics.FSharp doesn't work with F# 2.0 on .NET 4.0

### ISSUE THREAD

**Issue by wayoung** [mathnet/mathnet-numerics#299]
Contrary to the claims on the download site, MathNet.Numerics.FSharp does not seem to be compatible with .NET 4.0.0.0. Intellisense doesn't pick up any error, but when I try and build a project in FSharp with .NET 4.0.0.0, it says that it needs FSharp Core 4.3.1.0 or something like that. I tried this in VS 2010, and it did not work. Then I upgraded to VS2013 it seemed to work better, but my company can  only use VS2010 in production, which only goes up to .NET 4.0.0.0. It would be nice to have a version of MathNet.Numerics.FSharp that is truly dependent on version 4.0.0.0. Or at least, a warning put up on the site that only users of VS2012 and higher can use it because VS2010 can only handle 4.0.0.0 stuff.

**Comment by cdrnet** [comment]
Math.NET Numerics is primarily built against .Net 4.0 (although we also have a .Net 3.5 build, and some of the pcl builds target .Net 4.5), so it should definitively work to target .Net 4.0.

Could you provide a simple repro somewhere so I can have a look at it?

**Comment by cdrnet** [comment]
I've just verified, I can easily create an F# project targeting .Net 4.0 in the old VS 2012, install the MathNet.Numerics.FSharp NuGet package (which automatically brings FSharp.Core 4.3.1.0 as NuGet dependency) and have everything work as expected, with IntelliSense etc.

Please comment below if you still cannot make it work as expected. This is certainly a supported scenario.

**Comment by wayoung** [comment]
As I mentioned in my post, it does not work in VS2010. I think the Numerics build has a reference to an FSharp Core dll version that is not supported by VS2010. I just looked it up. It is only VS2012 and higher. So even though VS2010 can run .NET 4.0, it cannot use numerics. Please verify this.

**Comment by wayoung** [comment]
I just figured it out. When I install using

    Install-Package MathNet.Numerics.FSharp

It also installs FSharp.Core 3.1.2.1, which is not supported by Visual Studio 2010. It needs Visual Studio 2012 or higher. Thus, while it is compatible with .NET 4.0, it is not compatible with Visual Studio 2010. It will work perfectly in Visual Studio 2012 or Visual Studio 2013 in a .NET 4.0 build. Again, the problem only shows itself when I try to build an F# library.

**Comment by cdrnet** [comment]
Ah, I understand. VS 2010 fully supports F# 2.0 only, F# 3.0 is VS2012 and higher.

I expect it therefore to work if you create a project targeting .Net 3.5, since in this case we do bind against an older FSharp.Core version 2.3.0.0.

What could work in .Net 4.0 is to skip the FSharp.Core package (i.e. install MathNet.Numerics and .Fsharp manually instead of with NuGet) and then create a binding redirect to redirect FSharp.Core 2.3.0.0-3.1.2.1 to 2.3.0.0.
