### ISSUE TITLE
Documentation Question

### ISSUE THREAD

**Issue by wayoung** [mathnet/mathnet-numerics#300]
In the documentation, what is 'TU? As in:

Vector<T> Map<TU>(Func<double, TU> f, Zeros zeros)

I have no idea how to implement this in F#.

**Comment by cdrnet** [comment]
I suppose you're looking at the following method?

    public Vector<TU> Vector<T>.Map<TU>(Func<T, TU> f, Zeros zeros = Zeros.AllowSkip)

TU is usually the same as T, unless you want to convert between the types. For example, in C#:

    var u = Vector<Complex>.Build.Random(10); // Vector<Complex>
    var v = u.Map(c => c.Real); // Vector<double> - hence TU=double

The same in F#:

    let u = Vector<Complex>.Build.Random 10
    let v = u.Map (fun c -> c.Real)

With the F# extensions you can also write as follows, just like you could do with a set or list:

    let v = u |> Vector.map (fun c -> c.Real)
