### ISSUE TITLE
Trouble compiling f# example on osx/mono

### ISSUE THREAD

**Issue by sporring** [mathnet/mathnet-numerics#301]
Hi, I'm new to f# and mathnet-numerics, so apologies if I'm overlooking something simple: I'm using OSX 10.9.5, 

>$ mono -V
>Mono JIT compiler version 3.12.0 ((detached/a813491 Thu Dec 11 12:24:44 EST 2014)
>Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> TLS:           normal
> SIGSEGV:       altstack
> Notification:  kqueue
> Architecture:  x86
> Disabled:      none
> Misc:          softdebug 
> LLVM:          yes(3.6.0svn-mono-(detached/5486eb2)
> GC:            sgen

and have installed mathnet-numerics by nuget:
> mono nuget.exe install MathNet.Numerics -Pre -OutputDirectory ../packages

When I run the (slightly modified) example from (http://numerics.mathdotnet.com),

    #load "../packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx"
    open MathNet.Numerics
    SpecialFunctions.Gamma(0.5)
    open MathNet.Numerics.LinearAlgebra
    let m : Matrix<float> = DenseMatrix.randomStandard 50 50
    (m * m.Transpose()).Determinant()

in fsharpi, I get the expected output,
>[Loading /Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx]
>
>namespace FSI_0002.MathNet
>
>
>val m : MathNet.Numerics.LinearAlgebra.Matrix<float> =
>  DenseMatrix 50x50-Double
> -0,782852  -0,0577401    2,64067    -2,38088    1,02557  ..   -1,32979   -1,09048
> -0,848074   -0,993109   0,594163   -0,663665    1,49723  ..    0,83462    1,88152
>  -0,28439    -1,86915    1,92833    -1,83547  -0,133756  ..    1,35272  -0,260367
>  -1,17179  0,00183867  -0,830724   -0,416077   -1,15498  ..  -0,770131      1,403
>  0,887245    -1,86222    0,58186      1,5029   -1,03372  ..    1,47168    1,45822
> -0,358391    -1,32379   -1,41389    0,665114  -0,550968  ..   -1,26557   0,614117
>  -1,31298    0,193253    -2,0712  0,00819092   0,572461  ..    2,73788    1,74402
> -0,745659   0,0931965   0,346901     1,08122    0,41008  ..  -0,421103    2,13621
>        ..          ..         ..          ..         ..  ..         ..         ..
> -0,329307   -0,387201  -0,682495   -0,207147   0,947934  ..   0,256275   -1,01213
> -0,119732    -2,51172    1,37435    -1,45537   0,590776  ..   0,248947  -0,261441
> -0,479057    -0,41963  -0,552198   -0,253395     1,0641  ..   0,519894  -0,303812
> -0,0383274    0,191296  -0,452133   -0,744387   0,346103  ..   0,465479    -0,4351
>
>val it : float = 4.658632389e+63

but when I compile it, I get errors concerning fsi namespace:

>$ fsharpc det.fsx 
>F# Compiler for F# 3.1 (Open Source Edition)
>Freely distributed under the Apache 2.0 Open Source License
>
>/Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx(24,1): error FS0039: The namespace or module 'fsi' is not defined
>
>/Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx(25,1): error FS0039: The namespace or module 'fsi' is not defined
>
>/Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx(26,1): error FS0039: The namespace or module 'fsi' is not defined
>
>/Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx(27,1): error FS0039: The namespace or module 'fsi' is not defined
>
>/Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx(28,1): error FS0039: The namespace or module 'fsi' is not defined
>
>/Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx(29,1): error FS0039: The namespace or module 'fsi' is not defined
>
>/Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx(30,1): error FS0039: The namespace or module 'fsi' is not defined
>
>/Users/sporring/Desktop/PoP/packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx(31,1): error FS0039: The namespace or module 'fsi' is not defined

I would be grateful for any help. Thanks, Jon

**Comment by cuda** [comment]
Just a guess (I couldn't get to work on windows either but with a different error)
see the "Differences Between the Interactive, Scripting and Compiled Environments" section on
https://msdn.microsoft.com/en-us/library/dd233175.aspx

Perhaps the #r references are ignored.

**Comment by sporring** [comment]
Good hint: I wrapped the fsi.* code in MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx into a
```
#if INTERACTIVE
...
#endif
```
and now I can compile. That implies that compiled code will have no output on expression return, so I had to modify the example a bit. I enclose both files.

demo.fsx
```
#load "../packages/MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx"

open MathNet.Numerics
let v = SpecialFunctions.Gamma(0.5)
printfn "%g" v

open MathNet.Numerics.LinearAlgebra
let m : Matrix<float> = DenseMatrix.randomStandard 50 50
printfn "%s" (m.ToString "G5")
let d = (m * m.Transpose()).Determinant()
printfn "%g" d
```
MathNet.Numerics.FSharp.3.6.0/MathNet.Numerics.fsx:
```
#nowarn "211"
#I "packages/MathNet.Numerics/lib/net40/"
#I "packages/MathNet.Numerics.3.6.0/lib/net40/"
#I "packages/MathNet.Numerics.FSharp/lib/net40/"
#I "packages/MathNet.Numerics.FSharp.3.6.0/lib/net40/"
#I "../packages/MathNet.Numerics/lib/net40/"
#I "../packages/MathNet.Numerics.3.6.0/lib/net40/"
#I "../packages/MathNet.Numerics.FSharp/lib/net40/"
#I "../packages/MathNet.Numerics.FSharp.3.6.0/lib/net40/"
#I "../../packages/MathNet.Numerics/lib/net40/"
#I "../../packages/MathNet.Numerics.3.6.0/lib/net40/"
#I "../../packages/MathNet.Numerics.FSharp/lib/net40/"
#I "../../packages/MathNet.Numerics.FSharp.3.6.0/lib/net40/"
#I "../../../packages/MathNet.Numerics/lib/net40/"
#I "../../../packages/MathNet.Numerics.3.6.0/lib/net40/"
#I "../../../packages/MathNet.Numerics.FSharp/lib/net40/"
#I "../../../packages/MathNet.Numerics.FSharp.3.6.0/lib/net40/"
#r "MathNet.Numerics.dll"
#r "MathNet.Numerics.FSharp.dll"

open MathNet.Numerics
open MathNet.Numerics.LinearAlgebra

#if INTERACTIVE
fsi.AddPrinter(fun (matrix:Matrix<float>) -> matrix.ToString())
fsi.AddPrinter(fun (matrix:Matrix<float32>) -> matrix.ToString())
fsi.AddPrinter(fun (matrix:Matrix<complex>) -> matrix.ToString())
fsi.AddPrinter(fun (matrix:Matrix<complex32>) -> matrix.ToString())
fsi.AddPrinter(fun (vector:Vector<float>) -> vector.ToString())
fsi.AddPrinter(fun (vector:Vector<float32>) -> vector.ToString())
fsi.AddPrinter(fun (vector:Vector<complex>) -> vector.ToString())
fsi.AddPrinter(fun (vector:Vector<complex32>) -> vector.ToString())
#endif
```

**Comment by cdrnet** [comment]
I've added a [comment](http://numerics.mathdotnet.com/#F-and-F-Interactive) to clarify that loading the helper script is only needed (or useful) in F# interactive.
