### ISSUE TITLE
GammaLowerRegularizedInv incorrectly throwing ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by memura** [mathnet/mathnet-numerics#302]
SpecialFunctions.GammaLowerRegularizedInv is very occasionally throwing a ArgumentOutOfRangeException for parameters which are valid.

For example the following line consistently throws the exception.
var anum = SpecialFunctions.GammaLowerRegularizedInv(499/2.0, 0.99017589658972616);

This happens for version 3.6.0.0  running on Window7 64bit .Net version v4.0.30319
(when compiled in both visual studio 2013 and 2010 versions)
Stacktrace:
   at MathNet.Numerics.SpecialFunctions.GammaLowerRegularized(Double a, Double x)
   at MathNet.Numerics.SpecialFunctions.GammaLowerRegularizedInv(Double a, Double y0)

This only appears to happen for specific numbers.  Compare all of the below which work correctly and agree with matlab results for the same function to around 14 sig figs.

        var afun = SpecialFunctions.GammaLowerRegularizedInv(499 / 2.0, 0.99);
             afun = SpecialFunctions.GammaLowerRegularizedInv(499 / 2.0, 0.991);
             afun = SpecialFunctions.GammaLowerRegularizedInv(499 / 2.0, 0.99017589658972);

**Comment by adv12** [comment]
I'm seeing what I think is the same behavior.  I get the same stack trace, and the exception says, "Value must not be negative (zero is ok).  Parameter name: x."  Is there any ETA for a fix?

**Comment by memura** [comment]
Hello crdnet,

Re: mathnet-numerics/src/Numerics/SpecialFunctions/Gamma.cs 

on the example I gave earlier
var anum = SpecialFunctions.GammaLowerRegularizedInv(499/2.0, 0.99017589658972616);

... I don't know if this helps but increasing the number of iterations  from 10 to 20  at line 416 avoids the problem I observed.

A better solution would be to understand why the bloc and iteration between lines 472 to 481 does not converge in a stable manner.   I don't know the algorithm being used here but this is where the error is thrown because instead of converging x starts to diverge  away from the solution very strongly and becomes negative when the expected value was positive.

iterblock1 i = 0,   y= 0.0111124069441098, x =287.018375650637
iterblock1 i = 1,   y= 0.00988832466283074, x =287.782708682118
iterblock1 i = 2,   y= 0.00982428831922022, x =287.824963174363
iterblock1 i = 3,   y= 0.00982410341181816, x =287.825085539619
iterblock1 i = 4,   y= 0.00982410341027495, x =287.825085540641
iterblock1 i = 5,   y= 0.00982410341027473, x =287.825085540642
iterblock1 i = 6,   y= 0.00982410341027462, x =287.825085540642
iterblock1 i = 7,   y= 0.00982410341027451, x =287.825085540643
iterblock1 i = 8,   y= 0.00982410341027451, x =287.825085540643
iterblock1 i = 9,   y= 0.0098241034102744, x =287.825085540644

up to iteration 9 all seems well but it has not quite converged to return early

whileblock i = 0,   y= 0.00982410341042983, x =287.825085540538
whileblock i = 1,   y= 0.00982410341074969, x =287.825085540327
whileblock i = 2,   y= 0.00982410341138951, x =287.825085539904
whileblock i = 3,   y= 0.00982410341266693, x =287.825085539058
whileblock i = 4,   y= 0.00982410341522399, x =287.825085537366
whileblock i = 5,   y= 0.00982410342033802, x =287.825085533983
whileblock i = 6,   y= 0.00982410343056161, x =287.825085527216
whileblock i = 7,   y= 0.00982410345101337, x =287.825085513682
whileblock i = 8,   y= 0.00982410349191687, x =287.825085486614
whileblock i = 9,   y= 0.00982410357371943, x =287.825085432478
whileblock i = 10,   y= 0.00982410373733122, x =287.825085324205
whileblock i = 11,   y= 0.00982410406455025, x =287.825085107661
whileblock i = 12,   y= 0.00982410471898854, x =287.825084674573
whileblock i = 13,   y= 0.00982410602786288, x =287.825083808397
whileblock i = 14,   y= 0.009824108645621, x =287.825082076044
whileblock i = 15,   y= 0.0098241138811328, x =287.825078611339
whileblock i = 16,   y= 0.0098241243521624, x =287.825071681929
whileblock i = 17,   y= 0.00982414529425135, x =287.82505782311
whileblock i = 18,   y= 0.00982418717854916, x =287.825030105472
whileblock i = 19,   y= 0.00982427094760951, x =287.824974670201
whileblock i = 20,   y= 0.00982443848760073, x =287.824863799682
whileblock i = 21,   y= 0.00982477357507094, x =287.824642058728
whileblock i = 22,   y= 0.00982544377994654, x =287.824198577163
whileblock i = 23,   y= 0.00982678430946871, x =287.823311615398
whileblock i = 24,   y= 0.00982946584762334, x =287.821537697335
whileblock i = 25,   y= 0.00983483084083003, x =287.817989883076
whileblock i = 26,   y= 0.00984556849831131, x =287.810894342021
whileblock i = 27,   y= 0.00986707452538427, x =287.796703609762
whileblock i = 28,   y= 0.00991020965093037, x =287.768323544614
whileblock i = 29,   y= 0.00999697397490895, x =287.711569011519
whileblock i = 30,   y= 0.0101724932685354, x =287.598082331929
whileblock i = 31,   y= 0.01053161016611, x =287.371198501484
whileblock i = 32,   y= 0.011283097327883, x =286.917788814278
whileblock i = 33,   y= 0.0129268342864655, x =286.012400204991
whileblock i = 34,   y= 0.0168429570806065, x =284.207337017165
whileblock i = 35,   y= 0.0277691514657893, x =280.619994640458
whileblock i = 36,   y= 0.0672831807464567, x =273.535870711142
whileblock i = 37,   y= 0.254707789006053, x =259.725293815411
whileblock i = 38,   y= 0.844782221315961, x =233.498706913453
whileblock i = 39,   y= 0.999993927194452, x =186.342159020873
whileblock i = 40,   y= 1, x =111.076192348675
whileblock i = 41,   y= 1, x =21.3460203326526

in the while block the algorithm fails to converge blowing out on the next iteration calculating the GammaLowerRegularized( 249.5, -13.141695456054459);


setting the first iteration block as      for (int i = 0; i < 20; i++)
returns on iteration i = 10 and returns a good value, namely 287.825085540644


I don't know if this causes numerical problems in the calculation for other values but it at least fixes the immediate problem.

btw, thanks for all your work on the library ... it is much appreciated!

memura

**Comment by cdrnet** [comment]
Thanks a lot for the analysis!

**Comment by petemchugh** [comment]
I realize that this thread is a bit dated, but I'm having a similar problem with the Gamma.InvCDF function. It's generally been working smoothly, but throws an error now and then, e.g., using these inputs:

MathNet.Numerics.Distributions.Gamma.InvCDF(0.027531887247383816, 1, 0.94386227612563511).

The error is 'Value must not be negative (zero is ok).
Parameter name: x' and it is definitely a set of inputs that is sensible for a gamma.

I missed the recommended fix/workaround (invisible) from earlier in this thread, but any tips/tricks to get this working would be great. Thanks!

Pete

**Comment by arubiomoreno** [comment]
Hello.

I did not see this thread before, but this happened to me as well and it is now solved.
Check https://github.com/mathnet/mathnet-numerics/issues/442

Regards.

**Comment by cdrnet** [comment]
Thanks for linking the issue. I'm closing this one as well, since it has - finally - been fixed in master.
