### ISSUE TITLE
PERT method creates Beta distribution with range [0, 1], not [min, max]

### ISSUE THREAD

**Issue by david-in-perth** [mathnet/mathnet-numerics#321]
As discussed in the original pull request thread, #319, the Beta.PERT method returns a distribution object that doesn't conform to the given min/max/mode parameters (unless `min` = 0 and `max` = 1).

Specifically, it returns a two-parameter beta distribution with range of [0, 1]. This distribution would need to be scaled by `max - min` and translated by `min` in order to produce the desired PERT distribution.

Extending the Beta distribution class as described in #322 would enable a trivial fix to this issue.

**Comment by cdrnet** [comment]
We need to fix this before releasing v3.8
