### ISSUE TITLE
Generalise Beta distribution class to "4-parameter Beta distribution"

### ISSUE THREAD

**Issue by david-in-perth** [mathnet/mathnet-numerics#322]
As mentioned in #319, a more general form of the Beta distribution accepts 4 distribution parameters. This is a translated/scaled version of the 2-parameter Beta distribution.

I think it's reasonable to extend the current Beta distribution class to include the four-parameter case. It can still be backwards compatible, since the two-parameter Beta distribution is just a special case of the 4-parameter Beta distribution, with min=0 and max=1, so current two-parameter constructors could simply call the 4-parameter constructor(s).

Implementing this feature would enable a trivial fix to #321.

**Comment by cdrnet** [comment]
We need to implement this before releasing v3.8 (required for #321)

**Comment by cdrnet** [comment]
I propose to provide this as a separate distribution (composition) instead of extending `Beta`.
