### ISSUE TITLE
Redistribute symbols for native providers

### ISSUE THREAD

**Issue by tibel** [mathnet/mathnet-numerics#324]
For diagnosing native memory issues it would be helpful to have the debug symbols.

e.g. for MKL:
- libiomp5md.pdb
- MathNet.Numerics.MKL.pdb

Maybe as separate download.

**Comment by cdrnet** [comment]
The latter is available in the Zip file distribution ([release archive](http://1drv.ms/1NlUeDT)). The former we don't build ourselves, need to check whether we have symbol files for that one.

**Comment by tibel** [comment]
Thats exactly what I wanted.
Thanks

**Comment by tibel** [comment]
maybe README.md should point to http://1drv.ms/1NlUeDT instead of Codeplex.
Then I would have found it myself.

PS: libiomp5md.pdb is in the redist folder of Intel Parallel Studio XE nearby the dll

**Comment by cdrnet** [comment]
It is linked from the website at [NuGet & Binaries](http://numerics.mathdotnet.com/Packages.html). The Codeplex link will be dropped entirely soon as I've finally found a replacement for the old Codeplex discussion board.
