### ISSUE TITLE
MKL: lapack info variable is not handled correct

### ISSUE THREAD

**Issue by tibel** [mathnet/mathnet-numerics#327]
In multiple function/templates in `lapack.cpp` the value of `info` is not checked before continuing with other operations.

**Comment by tibel** [comment]
Also this needs to be checked in managed code, as only a value `zero´ means success (see https://software.intel.com/de-de/node/520868).

**Comment by cuda** [comment]
I started going through the `info` return values. What about cases such as `getrf`:
```
If info = 0, the execution is successful.
If info = -i, the i-th parameter had an illegal value.
If info = i, uii is 0. The factorization has been completed, but U is exactly singular. 
Division by 0 will occur if you use the factor U for solving a system of linear equations.
```
In this case, I don't think we should throw an exception if `info > 0`, no?

**Comment by tibel** [comment]
You are right, in this case it depends on what operation comes next (we can handle this later).

**Comment by cuda** [comment]
sorry for the delay, not much spare time lately...I pushed the error checking for LU factor and inverse as an example..
https://github.com/cuda/mathnet-numerics/tree/memory

**Comment by tibel** [comment]
Thanks.
