### ISSUE TITLE
Rename CompoundMonthlyReturn to CompoundReturn

### ISSUE THREAD

**Issue by grovesNL** [mathnet/mathnet-numerics#331]
The method name `CompoundMonthlyReturn` of [`AbsoluteReturnMeasures`](https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Financial/AbsoluteReturnMeasures.cs) implies that monthly data is necessary, but it's a generalized method that can be applied to any period. The method stub agrees that it is generalized ("Compound Monthly Return or Geometric Return or Annualized Return"). A more suitable name may simply be `CompoundReturn`.

**Comment by cdrnet** [comment]
Renamed in master - the old one is still there for compatibility reasons but marked as obsolete.

Thanks!
