### ISSUE TITLE
Ungraceful Mono crash under specific set of circumstences using MathNet.Numerics from F#

### ISSUE THREAD

**Issue by obadz** [mathnet/mathnet-numerics#332]
I've posted this on the F# compiler issues but not sure whether this could be a MathNet.Numerics issue.

Please see https://github.com/fsharp/fsharp/issues/426#issue-90449550 for a full description of the problem.

**Comment by cdrnet** [comment]
According to the linked issue this has been fixed upstream in Mono, so I think we can close this here. But thanks for reporting and making us aware of it!
