### ISSUE TITLE
Beta pdf returns NaN

### ISSUE THREAD

**Issue by esfahanoog** [mathnet/mathnet-numerics#337]
? Beta.PDF(176,210,0)
NaN

? Beta.PDF(176,210,.5)
NaN 

![betadist](https://cloud.githubusercontent.com/assets/13336781/8679910/eefbd3cc-2a72-11e5-8203-1c9bb5aa972b.png)

**Comment by cdrnet** [comment]
Thanks, for reporting - I can repro this locally.

**Comment by cdrnet** [comment]
Fixed in master, thanks again!

**Comment by esfahanoog** [comment]
Your welcome!
it wasn't possible for me to find your mail address
Would you please contact me (S.Hayati@sci.ui.ac.ir)
