### ISSUE TITLE
Sparse matrix addition fails

### ISSUE THREAD

**Issue by ThomasAuzinger** [mathnet/mathnet-numerics#341]
When executing the following code

```c#
// Build identical sparse matrices
var sparse = Matrix<double>.Build.Sparse(2, 2, (i, j) => i != j ? 1 : 0);
var sparse_copy = Matrix<double>.Build.SparseOfMatrix(sparse);
// Add one of them to itself
sparse += sparse;
// Check for differences
var sparse_enumerated = sparse.Enumerate(Zeros.Include);
var sparse_copy_enumerated = sparse.Enumerate(Zeros.Include);
if (Enumerable.SequenceEqual(sparse_enumerated, sparse_copy_enumerated))
    Debug.Log("Error");
```

the error message is logged. Thus, the `+=` operator had no effect and both matrices are identical. Since this does **not** happen with dense matrices (i.e., `dense += dense` doubles a dense matrix), I assume that this is unintended behavior.
Note that the alternative notation of `sparse.Add(sparse, sparse)` also works as expected (i.e., the sparse matrix is doubled).

I am using the Math.NET Numerics v3.4.0 dlls for the .NET Framework 3.5 as a plugin in Unity3D.

**Comment by cdrnet** [comment]
Thanks for reporting this - there was indeed a critical bug in an optimization path where both arguments are the same instance. I've fixed it in master and will release a NuGet patch package (most likely will be v3.7.1) later today.
