### ISSUE TITLE
% filling value on a Sparse Matrix of complex values

### ISSUE THREAD

**Issue by josesoyo** [mathnet/mathnet-numerics#347]
Hello,

There's something strange that I've seen on SparseMatrix.

When I initiate a sparse matrix with complex values, on the output the %filled is weird.
As an example, on F# interactive when I run:
```
let Csmat = SparseMatrix.init 2 2 (fun i j -> Complex(1.,2.))   
let Rsmat = SparseMatrix.init 2 2 (fun i j -> 2.)    

```

I obtain:
![mathdotnetcomplexmatrix](https://cloud.githubusercontent.com/assets/13557425/10727474/7c9e58b8-7bda-11e5-8970-6b7fb2c458af.png)

Sorry if this is not the place to post this, it may be that just simply it's not thought to work with complex values the sparse matrix
Jose

**Comment by cdrnet** [comment]
This was indeed a bug in SparseMatrix for Complex and Complex32, where the conversion to percentage was done twice by mistake, hence the reported percentage always too high by factor 100.

I've fixed the bug in master, thanks for reporting!
