### ISSUE TITLE
Distributions.Normal: results differ when calling static and non-static methods

### ISSUE THREAD

**Issue by Yenyenx** [mathnet/mathnet-numerics#348]
Hi,
Tests reveal that the implementation of static and non-static methods of the class Distributions.Normal differ, i.e. for small percentile values - e.g. up to 7 standard deviations, the values returned by the static cdf method converge very/too quickly towards 0 whereas the non-static method returns a value which is small but larger than 0 and which also complies with the value returns by MS EXCEL.

A quick code inspection reveals that static and non-static Normal.CDF methods differ when they call ErfImpl. One is calling Erf and the other one is calling Erfc. From a pure theoretical point of view both implementations should provide the same output but in practice rounding issues kick in, i.e. even when using double precision, for small percentile values, i.e. 7 std deviations or smaller, 1 - epsilon = 1 when 0 + epsilon <> 0.

A quick way to fix this difference would be to use the same ErfImpl for static and non-static methods, i.e. remove the boolean from the ErfImpl and keep the code of the non-static method which provide the expected results, i.e. compliant with MS EXCEL up to MS EXCEL numerical precision.

What do you think ?

**Comment by cdrnet** [comment]
Yes, indeed, both should use the same implementation, and we should avoid such potentially fatal subtractions (similar to the classical exp(x)-1 case).

I'll have a look at it. Thanks for reporting this!

**Comment by cdrnet** [comment]
Fixed in master, thanks again.
