### ISSUE TITLE
Build: create NuGet packages using Paket instead of NuGet.exe

### ISSUE THREAD

**Issue by cdrnet** [mathnet/mathnet-numerics#349]

**Comment by JohanLarsson** [comment]
Can paket create .symbol packages?

**Comment by cdrnet** [comment]
I don't think it does yet, maybe because GitHub source indexing seems to be more popular in that closer community. But symbol source packages do not look particularly complicated to me and I assume they'd accept a pull request for this.

**Comment by cdrnet** [comment]
We've switched to the newer Microsoft SDK where this is no longer a concern (nor a need).
