### ISSUE TITLE
The CUDA Runtime initialization failed

### ISSUE THREAD

**Issue by gareththegeek** [mathnet/mathnet-numerics#355]
I am receiving an error when calling `Control.UseNativeCUDA();` with the latest revision of the library.  I am attempting to use CUDA 7.0 on Windows 7 x64

The `SafeNativeMethods.createBLASHandle` call is returning `CUBLAS_STATUS_NOT_INITIALIZED`

**Comment by gareththegeek** [comment]
Please close this issue, the problem was that I was connecting to the machine using `Remote Desktop Connection`.  If I bother to stand up and actually walk over to the machine, everything runs fine!

**Comment by cdrnet** [comment]
Thanks for the update!
