### ISSUE TITLE
MersenneTwister off by one error

### ISSUE THREAD

**Issue by Plutonix** [mathnet/mathnet-numerics#359]
It may be that the MersenneTwister has some sort of off by one error.  I was using MathNet to verify some results, I was getting a mismatch.  After a day or two I now have 4 MT implementations.  Using a seed so each generates the same value(s), MathNet is off sometimes.  The "sometimes" is what is bothersome.  

It would appear that any seed value <= 274 results in an off by one error.  Example:  Using a seed of 42, the first random int is 804318770 while 3 other implementations return 804318771.  Seeds of 275-287 match but that is as far as I went.  It may start up again elsewhere.

The "other" implementations do not all have a great provenance, but they do agree.  One is the Troschuetz.Random package from NuGet, one is an old VBA translation and I cant recall where I got the other.

Its entirely possible they are all wrong, but with all 3 in agreement, I though I would pass it along.

**Comment by cuda** [comment]
The C reference implementation also returns 804318771.

http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/emt.html

**Comment by cuda** [comment]
I think I see the problem. I'll try to fix it this weekend.

**Comment by Plutonix** [comment]
The error does start up again in various places (testing 10million values). That page is where I got the VBA version; which I now have converted to VB.NET.  Negative int seed values are handled differently in Troschuetz vs MathNet.  S/he uses  Math.Abs(seed) which results in totally different values. I cant see that step in the C source, so it seems wrong there (and not your problem).

**Comment by cuda** [comment]
Our genrand_int32() method output matches the C code output perfectly. The problem is when we convert the double back to an int in RandomSource (DoSample()*int.MaxValue). We are generarting a 32-bit in the MT code, but converting it to a 31-bit in RandomSource. I think we should override Next in the MT class and generate the 31-bit int there as the C code does in genrand_int31 (genrand_int32()>>1). This would remove any rounding issues. The problem is that Next is sealed in RandomSource. @cdrnet Would it be problem to "unseal" the method?

**Comment by cdrnet** [comment]
The sealing currently helps ensuring some guarantees on the threading behavior.

Would it be an option to provide a `DoSample` overload in `RandomSource` for integer sampling instead, something along the lines of `protected virtual int DoSample(int minInclusive, int maxExclusive)`, with a base implementation of `(int)(DoSample()*(max-min))+min`? All integer routines would then use this overload internally, while the floating-point routines would continue calling the existing one. MersenneTwister could then override this overload, at least for the case where (minInclusive=0, maxExclusive=int.MaxValue).

Note that `Next` must never generate int.MaxValue. Is this consistent with the standard?

**Comment by cuda** [comment]
OK,  an int DoSample makes sense.

>Note that Next must never generate int.MaxValue. Is this consistent with the standard?
Right. I think what I suggested could return int.MaxValue.  hmm, thinking...

**Comment by cdrnet** [comment]
We already have cases where we simply reject/skip such numbers and call the sample routine (recursively) for the next number. This should not influence the distribution and randomness properties.

**Comment by cdrnet** [comment]
Related: in `MersenneTwister.DoSample` we divide by `uint.MaxValue+1` to avoid generating `1.0`.

**Comment by cuda** [comment]
>We already have cases where we simply reject/skip such numbers and call the sample routine 
>(recursively) for the next number. This should not influence the distribution and randomness properties.

OK, then what you suggested makes perfect sense.

> Related: in MersenneTwister.DoSample we divide by uint.MaxValue+1 to avoid generating 1.0.

That was in the reference code as well (it had methods to generate [0,1] and [0,1) )
