### ISSUE TITLE
Double precision is a real problem

### ISSUE THREAD

**Issue by StevePAC** [mathnet/mathnet-numerics#363]
![mathnetolsproblem](https://cloud.githubusercontent.com/assets/16633821/12221734/62939146-b775-11e5-95ea-429a516342cd.jpg)

Any work around?
Tracing the issue it appears that inv(x'*x) in MathNet is off vs. Matlab's version. I tried every each way and function MathNet results come out the same way. In fact, Excel's Linest generates exactly the same result as MathNet.

**Comment by cdrnet** [comment]
What exactly are you trying to do?

Matlab, Math.NET Numerics and Excel all use double precision. In fact almost all numerical software does. I'm not aware this has prevented any of them from being used in commercial software :)

**Comment by StevePAC** [comment]
I am doing a simple linear regression y=k*x+b  with intercept true. I took the slide from the internal circulation when we discussed this issue. Some regressions come out correct, while others are not - whatever Matlab is doing makes a difference.- hence a question about a work around.

**Comment by cdrnet** [comment]
What routines are you using in Matlab and Math.NET Numerics?

**Comment by cdrnet** [comment]
(sorry, clicked the wrong button)

**Comment by cdrnet** [comment]
May I ask what routines you use, both in Matlab and Math.NET Numerics?

**Comment by StevePAC** [comment]
Thanks for a quick response.

Data: x-input, y-output - both are vectors

Matlab: x = [ones(N,1),x]; b=x/y or b=inv(x'*x)*(x'*y) both generate the same answer
MathNet: append a column of 1's to x call it oneX (oneX.Transpose() * oneX).Inverse() * (oneX.Transpose() * y); or use MultipleRegression.everymethod(x,y,true) - all generate the same answer that is not equal Matlab's version.

**Comment by cdrnet** [comment]
For any of those cases where there are different results, how does `SimpleRegression.Fit(x,y)` compare to them?

**Comment by StevePAC** [comment]
No difference in results across platforms or functions. Excel generates the exact same answer as MathNet.

**Comment by cdrnet** [comment]
In Math.NET Numerics, do you use a native provider like MKL or just the managed one?

If Excel, Math.NET MultipleRegression and SimpleRegression (which are implemented very differently) all agree with each other, the odd one seems to be Matlab. Are you absolute sure you pass exactly the same data to these routines, with the same precision?

**Comment by StevePAC** [comment]
Not sure - I used nuget and whatever came along with it.
In Excel I used a native linest function and do not have MathNet installed - I only used it to confirm I am comparing apples to apples and as a sanity check.

**Comment by cdrnet** [comment]
See http://numerics.mathdotnet.com/MKL.html. With the MKL provider enabled you get practically the same implementation that Matlab is using (on `MultipleRegression.XY`).

**Comment by StevePAC** [comment]
Thanks I will check it out. Any performance metrics for it for comparison?

**Comment by StevePAC** [comment]
Got an exception from Matrix<decimal>: "Matrices and vectors of type 'Decimal' are not supported. Only Double, Single, Complex or Complex32 are supported at this point." 

Might as well say intended for children ages 6-12 only.

I have never seen any serious math calculations working with double consistently. Not to be mean, but spent a lot of time integrating the lib that now needs to be ripped out by the looks of it..I would add Decimal asap.

**Comment by cdrnet** [comment]
Let me ignore the claim that apparently the entire scientific community and software industry around numerical methods is not doing "serious math calculations". I'd be very surprised if this is related to numerical precision at all. Even more so since Matlab is using double/extended precision as well.

Any chance you could provide a simple dataset where I could repro the issue?

**Comment by Superbest** [comment]
This is thread is a bit confusing.

Are there supposed to be axis labels on the figure? And what is it supposed to show?

I agree with cdrnet that double is good enough for plenty of scientific and commercial applications. Of course you can devise scenarios where double precision is challenged and aberrant behavior occurs. It's a bit of a leap to go from that and claim that double is not sufficient for any calculation, or that you "might as well say intended for children ages 6-12 only".

**Comment by kjbartel** [comment]
> I have never seen any serious math calculations working with double consistently. Not to be mean, but spent a lot of time integrating the lib that now needs to be ripped out by the looks of it..I would add Decimal asap.

Before you rip it out you may actually want to try and find another library which does support `decimal`. I don't know of any in .Net or C/C++ (or any other language for that matter). Decimals are not implemented in hardware so are very slow for doing a large number of calculations. They also have a lot smaller range.
