### ISSUE TITLE
NextFullRangeInt32() on MersenneTwister does not seem to work properly

### ISSUE THREAD

**Issue by GabrielSandor** [mathnet/mathnet-numerics#368]
I want to generate a full range of integer numbers in random order (that is, from int32.MinValue to int32.MaxValue inclusive, with everything in-between) using `MersenneTwister`, however the following call seems to return duplicates sooner than it should:

   ```
var random = new Random();
var mersenneTwister = new MersenneTwister(random.Next());
   
   for (ulong i = 1; i <= (ulong)uint.MaxValue + 1; i++)
   {
         var number = mersenneTwister.NextFullRangeInt32();

          // check if number was already generated             
   }
```

I'm using a bit vector to track duplicates. The number of iterations until a duplicate is returned varies each time i rerun this code, however if i use 0 as the seed, the duplicate number 312749827 is returned after 179263 iterations.

I tested with `Next()` as well and it also returns duplicates sooner than it should.

Could there be a bug in the implementation or am i not using it correctly?

**Comment by cdrnet** [comment]
Just to clarify, this is about a single duplicate sample, not a cycle (i.e. the next sample after that is not a duplicate)?

**Comment by GabrielSandor** [comment]
In order to test the code above i wrote a unit test with NUnit which fails whenever a duplicate is found and halts execution. I didn't check for additional duplicates, or cycle duplicates, but now if i prevent the assertion failure it seems that there are more than 1 duplicate throughout the iteration. Would it help if i checked that there are exact cycle duplicates? I hope i understood your question correctly.

**Comment by cdrnet** [comment]
With the question I tried to find out whether there is just a repeated sample (which would be ok) or actually a repeated internal state and thus a cycle where the same numbers are returned again in the same order (which would indeed be very bad).

You mentioned you got a duplicate earlier than expected. At what point would you expect them to happen?

Given the birthday problem, unless I made a mistake in my formula or assumptions, for `Next` I'd actually expect a duplicate after 54562 samples, for `NextFullRangeInt32` after 77163 samples.

Here's the code I've used:

```C#
double ProbabilityOfDuplicate(double samples, double population)
{
    return 1.0 - Math.Exp(
    SpecialFunctions.GammaLn(population + 1.0)
    - SpecialFunctions.GammaLn(population - samples + 1.0)
    - samples * Math.Log(population));
}
```

This leads to

```
ProbabilityOfDuplicate(179263, Int32.MaxValue)
-> 99.94%

ProbabilityOfDuplicate(179263, Int32.MaxValue - (double)Int32.MinValue)
-> 97.62%
```

Or, for the number of samples with a probability of 50%:

```
FindRoots.OfFunction(n => ProbabilityOfDuplicate(n, Int32.MaxValue) - 0.5, 1000.0, 100000.0)
-> 54562.5

FindRoots.OfFunction(n => ProbabilityOfDuplicate(n, Int32.MaxValue - (double)Int32.MinValue)-0.5, 10000.0, 200000.0)
-> 77163.2
```

**Comment by GabrielSandor** [comment]
What i was actually asking is, shouldn't the Mersenne Twister have a period high enough so that if you call Next() 2^32 times in a row, it doesn't return duplicates? Assuming a 32-bit implementation, as seems to be the case here.

**Comment by cdrnet** [comment]
No. While the period should indeed be very large, that does not imply that single samples may not be repeated within the period. A repeated sample does not imply that a period has ended, provided the internal state is much larger.

In fact, the probability of the sequences {1, 2, 3} and {1, 1, 1} should be the same, otherwise the samples would not be independent from each other (i.e. correlated). If it would not return any duplicates within a period, as you proposed, every sample would result in information about all following samples (which would be a critical problem in cryptography).

It seems to me what you're looking for is something more along the lines of `Combinatorics.GenerateVariation`, although this particular implementation does unfortunately not work at all in your use case. Maybe it would be feasible instead to just detect and skip duplicates?

**Comment by Jdsleppy** [comment]
This is the source of the behavior:

> Although PRNGs will repeat their results after they reach the end of their period, a repeated result does not imply that the end of the period has been reached, since its internal state may be larger than its output; this is particularly obvious with PRNGs with a one-bit output.
-[Wikipedia](https://en.m.wikipedia.org/wiki/Pseudorandom_number_generator)

The implementation for `NextFullRangeInt32()` in Math.NET seems to destroy the algorithm's period for the sake of extending its range.  It finds 4 integers in the range `[0, int.MaxValue-1]` (the typical int you get from the object) then down-converts them to bytes by taking the modulo 256, then constructs a full range 32-bit integer from the four bytes.  You can see how the modulo operation will cause the output to be repeated even though the algorithm's internal state has not repeated yet: the "blame" lies in the extension method `NextFullRangeInt32()`, not the Mersenne Twister implementation.

**Comment by GabrielSandor** [comment]
@cdrnet : It seems then that i was misinformed, the original advice to use the Mersenne Twister came in [this](http://stackoverflow.com/a/35102979/475673) StackOverflow thread. Or maybe it's possible to use it for the purpose of generating all 32-bits integers in non-repeating and random order but i don't use it correctly.

@Jdsleppy: I suspected `NextFullRangeInt32()` would behave so but only after browsing the source code. However, i noticed the same duplication behaviour for `Next()` as well.

**Comment by GabrielSandor** [comment]
After all there doesn't seem to be a problem with the Mersenne Twister implementation, i just tried to use it in a scenario it doesn't really fit in.

**Comment by cdrnet** [comment]
Interesting thread, thanks for the update. I'd actually be interested in an alternative implementation of `Combinatorics.GenerateVariation` that would work in this case, so please do let me know if you find a good solution :).

**Comment by GabrielSandor** [comment]
I'll update the thread as i test the suggested answers, right now the most promising and feasible solution seems to be Linear Congruential Generator, although you couldn't say it produces higher quality random numbers than the Mersenne Twister. I'll try to test 1 or 2 more proposed solutions and then pick the one that i consider the most appropriate.

Sorry for ringing a false alarm and opening this issue thread.
