### ISSUE TITLE
MathNet.Numerics NuGet package not working with project.json

### ISSUE THREAD

**Issue by kjbartel** [mathnet/mathnet-numerics#372]
NuGet 3.x has [added support for project.json for describing project dependencies](http://docs.nuget.org/Consume/ProjectJson-Intro). By default ASP.Net 5, Portable class libraries and UWP projects created in Visual Studio 2015 will use this format instead of the old packages.config. However other types of projects can also be [changed to use project.json](https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json).

I thought I'd try it out so changed a unit test project over to using project.json which was using Xunit and MathNet.Numerics. Xunit and the Xunit.runner.visualstudio installed fine and I could run the unit tests without any problems. But when I added MathNet.Numerics v3.10.0 it completely broke the project. For some reason the `System` reference can no longer be resolved and the project can't be built.

The project is targeting .Net 4.6.1 so I thought it might be because of how the portable targets are defined for MathNet.Numerics. To test I made a new C# class library project targeting .net 4.0 and added a simple test class which included the use of `INotifyPropertyChanged`. With no nuget packages installed the library built correctly. Installing MathNet.Numerics in this project again also gave errors.

> error CS0234: The type or namespace name 'ComponentModel' does not exist in the namespace 'System' (are you missing an assembly reference?)
> error CS0246: The type or namespace name 'INotifyPropertyChanged' could not be found (are you missing a using directive or an assembly reference?)

I'm really not sure if this is a NuGet / msbuild / Visual Studio bug or a problem with the MathNet nuget package(s). Either way I thought it should be brought to your attention.

On a side note, project.json support in NuGet seems to address a lot of the same things which paket does. Would you consider moving to NuGet with project.json instead of paket (assuming this issue can be solved)?

**Comment by cdrnet** [comment]
if your project is targeting .Net 4.6.1, then it must use the .Net 4.0 build of Math.NET Numerics, not one of the portable ones. Can you find out which one actually does gets used? (If this makes any sense - to my understanding, which one gets used for compilation and at runtime can actually differ in a project.json style setup)

**Comment by cdrnet** [comment]
NB: I'm very happy with Paket and quite unhappy with some of the design decisions around project.json and NuGet, so there are currently no plans to move back (but this can change, of course).

**Comment by jasonmalinowski** [comment]
This is just another manifestation of NuGet/Home#1880. A workaround is discussed there while people are waiting to consume the fix.

**Comment by kjbartel** [comment]
@jasonmalinowski Thanks for that.

Adding, `<IncludeFrameworkReferencesFromNuGet>false</IncludeFrameworkReferencesFromNuGet>` to the project file worked for me.
