### ISSUE TITLE
MersenneTwister results are inconsistent between platforms

### ISSUE THREAD

**Issue by chrismacklin** [mathnet/mathnet-numerics#383]
The System.Random RNG is inappropriate for cross-platform development as its results for the same seed differ between .NET and mono (and could even differ between .NET versions).  I was hoping to switch over to the MathNet MersenneTwister implementation to sidestep this, but it appears that I am still getting inconsistent results between the two for the same seed.  Is this expected behavior?

**Comment by cdrnet** [comment]
No, when providing the same seed this is not expected (to my understanding). Can you provide a simple repro?

**Comment by chrismacklin** [comment]
After construction of a minimal test setup, we weren't able to reproduce this.  It is likely our output differences between platforms are not due to RNG differences.  Closing.

**Comment by cdrnet** [comment]
Thanks for the update!
