### ISSUE TITLE
Vector ToVectorString(int,int,string,string,string,Func<T, string>) throws exception for formatValue giving longer strings than maxWidth

### ISSUE THREAD

**Issue by PawelTroka** [mathnet/mathnet-numerics#387]
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MathNet.Numerics.LinearAlgebra.Vector`1.ToVectorStringArray(Int32 maxPerColumn, Int32 maxWidth, Int32 padding, String ellipsis, Func`2 formatValue)

Code below reproduces it nicely.

            MathNet.Numerics.LinearAlgebra.Vector<double>.Build.DenseOfArray(new []
            {
                0.607142857142857,
                1.17857142857143
            }
        ).ToVectorString(12, 12, "..", "  ", "\n", x => x.ToString());

Maybe it is a bug, maybe not, it depends on design choices.

**Comment by cdrnet** [comment]
Yes, that indeed looks like a bug, thanks for reporting!

**Comment by cdrnet** [comment]
Fixed in mainline. This issue was that due to the use of `x => x.ToString()` even the first column was wider than 12 characters. This is now handled more gracefully (always prints at least one column, and more sensible minimum limits). Thanks again for reporting.
