### ISSUE TITLE
Bug in sparse vectors

### ISSUE THREAD

**Issue by OpportunityLiu** [mathnet/mathnet-numerics#390]
The following result is made by csi.exe

> var a = CreateVector.Sparse(4, 2.0);
> Console.WriteLine(a);
SparseVector 4-Double 100.00% Filled
2
2
2
2

> Console.WriteLine(a.PointwiseMultiply(a));
SparseVector 4-Double 0.00% Filled
0
0
0
0

> Console.WriteLine(a);
SparseVector 4-Double 100.00% Filled
4
4
4
4

Shouldn't the value of `a.PointwiseMultiply(a)` be `[4, 4, 4, 4]` and the value of  `a` keep `[2, 2, 2, 2]` ?

**Comment by cdrnet** [comment]
That looks wrong indeed, thanks for reporting. I'll have a look at it!

**Comment by cdrnet** [comment]
Fixed in mainline, thanks again for reporting!
