### ISSUE TITLE
Hangs with integer matrix

### ISSUE THREAD

**Issue by davenportw15** [mathnet/mathnet-numerics#392]
The following code runs correctly:

    let m = matrix [[1.0; 2.0]
                    [3.0; 4.0]]

    printfn "%A" m

However, upon changing ``m`` to integer values, the program hangs: 

    let m = matrix [[1; 2]
                    [3; 4]]

    printfn "%A" m

``Matrix<float>`` works correctly, but there seems to be an issue with ``Matrix<int>``.

**Comment by cdrnet** [comment]
That looks like a bug to me. It is correct that it doesn't work with integers, but it should throw an exception. Thanks for reporting this!

**Comment by cdrnet** [comment]
I tried to reproduce the hang but failed. Instead a got an exception as expected:

    System.TypeInitializationException: ---> System.NotSupportedException:
    Matrices and vectors of type 'Int32' are not supported.
    Only Double, Single, Complex or Complex32 are supported at this point.

Can you try to provide a repro where this causes a hang?
