### ISSUE TITLE
namespace/module App not defined

### ISSUE THREAD

**Issue by drcrook1** [mathnet/mathnet-numerics#395]
New project, loaded into F# Interactive, and am not able to load MathNet.Numerics.IfSharp.fsx

Does not work in Profile 7 or standard console app.

`#load @"C:\projects\TradingApp\TradingApp\packages\MathNet.Numerics.FSharp.3.11.1\MathNet.Numerics.fsx"

//Issue on this line.
# load @"C:\projects\TradingApp\TradingApp\packages\MathNet.Numerics.FSharp.3.11.1\MathNet.Numerics.IfSharp.fsx"

open MathNet.Numerics
open MathNet.Numerics.IfSharp

let m = matrix [[ 1.0; 4.0; 7.0 ]
                [ 2.0; 5.0; 8.0 ]
                [ 3.0; 6.0; 9.0 ]]

let v = vector [ 10.0; 20.0; 30.0 ]`

**Comment by drcrook1** [comment]
Also having issues trying to reference raw .dll.  Appears I need a reference to System.Runtime.Numerics , which does not appear to be available.

I am in a Xamarin PCL profile 7 project.

**Comment by drcrook1** [comment]
This is a blocking issue for authoring our ML algorithms for mobile platforms.

**Comment by cdrnet** [comment]
Quick question: did Xamarin try to load `MathNet.Numerics.IfSharp.fsx` automatically or did you try to load it manually? This file is only intended for [IfSharp](https://github.com/fsprojects/IfSharp/), the F# profile/kernel for IPython Notebook/Jupyter, see [IF# Notebook - Math.NET Numerics Docs](http://numerics.mathdotnet.com/IFSharpNotebook.html).

**Comment by cdrnet** [comment]
It [seems](http://numerics.mathdotnet.com/Compatibility.html) that the F# package only supports PCL profile 47, not profile 7. But I need to check why, maybe we can add profile 7 as well (the core package supports profile 7 explicitly).
