### ISSUE TITLE
MathNet.Numerics.Sorting throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by technosight** [mathnet/mathnet-numerics#402]
V3.11.1, Intel MKL x86 rev 9
While sorting collections with 500+ items occasionally throws exception. Note - the exception isn't thrown every time, sometimes it works, sometimes it doesn't using exactly the same parameters, hence unpredictable.

MathNet.Numerics.Sorting.Sort<double, DenseVector>(keys, items, startIndex, count, Comparer<double>.Default)

Where keys and items are collections with 500 items and both startIndex and count equals to 100.

**Comment by cdrnet** [comment]
I have tried to reproduce but failed. Can you try to provide a repro?
