### ISSUE TITLE
Directly accessing data in multiplication of sparse with dense matrix

### ISSUE THREAD

**Issue by arthurvb** [mathnet/mathnet-numerics#408]
Currently, in the DoMultiply-function of SparseMatrix, if you multiply with a dense matrix, copies of the columns of the dense matrix are made (via other.Column(column, columnVector); ) after which the actual calculations are done.

It is possible to check the storage first and if the storage is DenseColumnMajorMatrixStorage<double> or DenseColumnMajorMatrixStorage<float>, you can directly do your calculations using the underlying Data-array.

We have implement this locally and it gives us major speed improvements (in the multiplication of these matrices). Does it make sense to initiate a pull request, or are there reasons for making these copies anyway?

With best regards,

Arthur

**Comment by cdrnet** [comment]
Some of the code paths around sparse matrices are known to be very poor performance-wise. Any improvement in this area is therefore very welcome. Please do open a pull request.

Checking for the storage format is a common pattern and is fine.

**Comment by cdrnet** [comment]
Closed since PR #409 has been opened. Thanks again.
