### ISSUE TITLE
Gauss-Legendre Quadrature error on order = 256

### ISSUE THREAD

**Issue by kbancroft** [mathnet/mathnet-numerics#414]
First post for me!  Came across a bug in MathNet.Numerics.Integration

I am getting an error when I try to generate a new GaussLegendreRule with order = 256.  No errors on any other amount (tested to 5000).  Left and right bounds do not seem to matter (even setting them equal).  Since 256 is one of the pre-calculated orders, it's probably an issue with the hard-coded values.  Stumbled across this when I was running a loop to get a feel for how long the calculations take (they're quite fast otherwise).

I'm happy to provide additional information if needed.

Sample code (VB.NET)
```
Dim Gvars As GaussLegendreRule
...
Gvars = New GaussLegendreRule(-1, 1, 256)
```
`
Message=Index was outside the bounds of the array.`
From the documentation:
> Approximates a definite integral using an Nth order Gauss-Legendre rule. Precomputed Gauss-Legendre abscissas/weights for orders 2,..., 20, 32, 64, 96, 100, 128, 256, 512, 1024 are used, otherwise they're calulcated on the fly.

**Comment by cdrnet** [comment]
Thanks for reporting this. Turns out this has already been fixed on master in #399 but not released yet. I plan to create a new release in a couple days.
