### ISSUE TITLE
CryptoRandomSource DoSample can return 1.0

### ISSUE THREAD

**Issue by marklam** [mathnet/mathnet-numerics#418]
The random number is generated by multiplying a randomly-generated Uint32 by `1.0/uint.MaxValue.`
If the randomly-generated Uint32 is uint.MaxValue, then DoSample will return 1.0 (which also has an effect on function generating random numbers within a range)
Reciprocal should (I think) be 1.0/(1.0+uint.MaxValue)

**Comment by cdrnet** [comment]
Yes, returning 1 would indeed be a bug. Thanks for reporting this.

**Comment by cdrnet** [comment]
Fixed in mainline. Thanks again for reporting.
