### ISSUE TITLE
Math.NET Numerics VS other mathematical tools

### ISSUE THREAD

**Issue by kapil-iitk** [mathnet/mathnet-numerics#419]
What is the difference between Math.NET, ILNumerics, IMSL and other similar tools (in comparison with their speed, simplicity, performance etc. ). I am currently using ILNumerics and NumPy for my scientific tool development and now want to switch to this library.

**Comment by kapil-iitk** [comment]
I found one link that compares math.net and ILNumerics. (http://blog.csdn.net/hacky_way/article/details/8066372). I am surprised to know that ILNumerics is faster. Is there any way to make math.net more faster.

**Comment by cdrnet** [comment]
For a start you can enable one of our native providers, e.g. the MKL provider.

Closing this since this is not a specific concrete issue, but feel free to open a topic at [discuss.mathdotnet.com](http://discuss.mathdotnet.com) to discuss this further.
