### ISSUE TITLE
Can be considered as alternative of MATLAB/ILNumeric Library

### ISSUE THREAD

**Issue by kapil-iitk** [mathnet/mathnet-numerics#422]
Is this library can be considered as alternative of ILNumeric or MATLAB (except visualization part)?
(if no, how matlab commands can be wrapped around mathnet-numerics?)

**Comment by Superbest** [comment]
Many computations that are commonly done in MATLAB can also be done in MathNET.

As for simply wrapping a bunch of MATLAB commands, I doubt it. In my experience MATLAB code needs to be rewritten from scratch when porting to MathNET, though most of that is quite straightforward.

**Comment by cdrnet** [comment]
Math.NET Numerics is designed for software developers which use it within a powerful programming language like C# or F#. This is a different scenario to MATLAB and results in a very different API design (and design goals).

So yes, as Superbest wrote, it can be used as alternative for common problems, but the feature set is of course smaller and it requires some one-time translation effort.

There are other .Net libraries, like the ILNumerics you mentioned, which are to my understanding much closer to MATLAB and would thus require less translation effort.
