### ISSUE TITLE
Math.NET Numerics without System.Threading?

### ISSUE THREAD

**Issue by skryshi** [mathnet/mathnet-numerics#425]
Is there a build of Math.NET Numerics that doesn't use System.Threading? Alternatively, is it easy to remove that dependency from the source?

I am trying to use Math.NET Numerics in Unity builds for WebGL, and it doesn't support multi-threading.

**Comment by cdrnet** [comment]
Multi-threading is quite fundamental in Numerics. However, direct usage of System.Threading is limited to a few places. The code base can already handle the single-thread case, enforced with `Control.UseSingleThread()`, so it should technically be possible to build it with only this option. However, this has not been realized in a custom build configuration yet.

**Comment by skryshi** [comment]
I see. Thanks for quick answer.

I found an old version of Math.Net that doesn't require multi-threading:
http://mathnetiridium.codeplex.com/
