### ISSUE TITLE
Result of RandomSource.Next(x, x+1) Not in Range [x, x+1[

### ISSUE THREAD

**Issue by Genmutant** [mathnet/mathnet-numerics#427]
Using MathNet.Numerics 3.13.0:

When I use the code `RandomSource.Next(x, x+1)`, I don't get the expected value of x back, but something (random) out of range.

Testcode:
```
RandomSource source = new Xorshift();
var next = source.Next(9, 10);
next.Should().Be(9); // Expected value to be 9, but found -2037414154.
```

Maybe there should be a fastpath added, to just return the minimum element without a random call?

**Comment by Genmutant** [comment]
The problem seems to be, that `DoSampleInt32WithNBits` is called with the parameter `bitCount=0`, and it tries to shift with an invalid amount of 32 bits:
```
// the least significant N bits with independend uniform distribution and the remaining bits zero
            uint uintN = uint32 >> (32 - bitCount);
```
Which leaves `uintN` the same as `uint32`.

**Comment by cdrnet** [comment]
Thanks for catching and reporting this!

**Comment by cdrnet** [comment]
Merged to master
