### ISSUE TITLE
Matrix<double> Inverse fails

### ISSUE THREAD

**Issue by Goicox** [mathnet/mathnet-numerics#432]
I am new using MathNet.Numerics. I would like to calculate the pseudo-inverse of A*A'. The resulting product is a square matrix. 

In the following example .Inverse fails because the matrix is close to singular or badly scaled.

(A * A.Transpose()).Inverse()

B = A * A'
B = ...
[0.25295692838587958 0.61194073916551683
0.61194073916551683 1.4803764049474544]

Is it possible to compute the pseudo-inverse of this type of matrices? 
Kindly advise. Goicox

**Comment by wo80** [comment]
The Inverse() method uses the LU decomposition, which isn't appropriate to compute the pseudo-inverse. You could try the QR decomposition or SVD instead, see https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_pseudoinverse#The_QR_method

**Comment by Goicox** [comment]
Thank you for your reply. I have implemented the pseudo-inverse as shown below. The results are the same as obtained with Matlab. 

I took the procedure from:
http://feedback.mathdotnet.com/forums/2060-math-net-numerics/suggestions/2667112-add-moore-penrose-pseudoinverse


`        // Compute the Moore–Penrose pseudoinverse
        public static Matrix<double> Pinv(Matrix<double> M)
        {
            // Computes the pseudo-inverse of M

            var svd = M.Svd(true);
            Matrix<double> W = (Matrix<double>)svd.W;
            Vector<double> s = (Vector<double>)svd.S;

            // The first element of W has the maximum value. 
            //double tolerance = MathNet.Numerics.Precision.EpsilonOf(2) * Math.Max(M.RowCount, M.ColumnCount) * W[0, 0];
            double tolerance = Math.Max(M.RowCount, M.ColumnCount) * M.L2Norm() * MathNet.Numerics.Precision.DoublePrecision;

            for (int i = 0; i < s.Count; i++)
            {
                if (s[i] < tolerance)
                    s[i] = 0;
                else
                    s[i] = 1 / s[i];
            }
            W.SetDiagonal(s);

            // (U * W * VT)T is equivalent with V * WT * UT 
            return (Matrix<double>)(svd.U * W * svd.VT).Transpose();
        }`

**Comment by cdrnet** [comment]
Finally implemented in master, with a small optimization to reuse the SVD to compute the norm.

**Comment by premsh** [comment]
Okay, I am pretty sure this is not the best place to ask a question but I will do it anyway in the hope of some form of answer. 

Is there a way to solve the inverse of the positive matrix so that the inverse matrix is non-negative? Or what's out there to ensure that we can try again and again to end up with non-negative matrix in the most efficient manner?
