### ISSUE TITLE
Refactoring the entire code

### ISSUE THREAD

**Issue by gandarez** [mathnet/mathnet-numerics#457]
Hey guys,
Are you open to accept PR of refactoring? I can see a lot of defined types instead of var.

**Comment by MovGP0** [comment]
I would not ask for permission. 

Just make the PR such that it can be peer reviewed. 

If you make a refactoring, than I recommend to stick to refactoring either, only a single class or a single/specific type of refactoring for the whole solution at a time. When the changes are merged you make the next refactoring.
