### ISSUE TITLE
Remove TestData dependency on .NET 3.5 for .NET 4+ builds.

### ISSUE THREAD

**Issue by davidfgarcia** [mathnet/mathnet-numerics#461]
When building MathNet.Numerics.sln in its current form, project TestData introduces a dependency on .NET 3.5; ideally, .NET 3.5 should not be required for .NET 4+ builds.

**Comment by davidfgarcia** [comment]
When building MathNet.Numerics.sln in its current form, project TestData introduces a dependency on .NET 3.5; ideally, .NET 3.5 should not be required for .NET 4+ builds.

**Comment by cdrnet** [comment]
TestData no longer depends on .Net 3.5 (in fact we no longer support 3.5 at all).
