### ISSUE TITLE
Serializable RandomSources

### ISSUE THREAD

**Issue by eropple** [mathnet/mathnet-numerics#462]
Hey folks--

First off, thank you so much for MathNet.Numerics--I love this library and it's helped me out a ton.

Plaudits aside, now for my beef. ;) I am using MathNet.Numerics for a project that, tied with my own [DiceNotation.MathNet](https://github.com/eropple/DiceNotation) library, uses RandomSources for game random number generation. I want to preserve the state of my RandomSources for the next run of the game, to prevent save scumming. Right now, this is...tricky.

A lot of algorithmic stuff in this package has public fields, but the fields in the classes that inherit from RandomSource seem to mostly be private. And that's fine by me from an encapsulative perspective, but it makes serializing this stuff _really hard_. I'd love to help make this a little easier. I see two ways to do this:

- The bad option: make the generators' internal fields publicly visible and having an external serializer/deserializer.

- The good option: include serialization (maybe just DataContract, as it's already PCL) attributes on the classes in question. Right now, I basically do this by copy/pasting these generators into my own code, using the MathNet RandomSource interface, and doctoring my forks, but that's gross.

Thoughts? Happy to do the work myself.

**Comment by cdrnet** [comment]
We have recently added basic serialization support (DataContract/Member and Serializable attributes) to a few types, e.g. [Histogram](https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Statistics/Histogram.cs#L258), with the explicit notion that this is intended to enable _ephemeral_ serialization only, i.e. serialization and deserialization with the same versions without any backward/forward compatibility guarantees. I'd be open to do the same for random sources.

Do you have strict requirements beyond _ephemeral_ serialization?

**Comment by eropple** [comment]
Not me. I expect that these interfaces probably wouldn't change much anyway--Xorshift isn't going to stop being Xorshift anytime soon. =)

**Comment by cdrnet** [comment]
Implemented in d9f8929. Thanks for proposing this!
