### ISSUE TITLE
Make CopySubRowToUnchecked in SparseCompressedRowMatrixStorage aware of underlying sparse storage

### ISSUE THREAD

**Issue by arthurvb** [mathnet/mathnet-numerics#465]
When getting a row-vector from a Matrix, the implementation uses CopySubRowToUnchecked to get the certain row. This is currently quite slow for sparse-matrices. However, if we can make the sparse-implementation aware that it is copying to a sparse row, this could result in an improvement in speed.

The use-case here is for (sparse) adjacency matrices, for which some algorithms need to do some processing on single rows.

I can implement the change here if you think this might be useful for others.

Best regards,

Arthur

**Comment by cdrnet** [comment]
Ideally all of these variations should have specific implementations for sparse data storage, so this would certainly be welcome and helpful!

**Comment by cdrnet** [comment]
Implementation merged, thanks again!
