### ISSUE TITLE
Determinant error

### ISSUE THREAD

**Issue by Giacomo1989ITA** [mathnet/mathnet-numerics#466]
Hi all,
I am wondering if the method Determinant() in namespace MathNet.Numerics.LinearAlgebra has some calculus issue.

With this 9x9 matrix:
-12604984.0868492 4607922.70918154 9144925.38542238 14245144.4847638 -4938617.63788385 -9580867.29659881 -1640160.39791456 -16546506.832626 -703744.778995006 ;
4607922.70918154 -1637967.24867097 -3303925.85122784 -5103618.69084115 1770150.26203667 3431284.086764 495695.981659611 5938950.61774783 217082.535858656 ;
9144925.38542238 -3303925.85122784 -6597834.9245516 -10242211.2619113 3552015.02297816 6888031.73340592 1097285.87648895 11908435.8473814 472266.490672735 ;
14245144.4847638 -5103618.69084115 -10242211.2619113 -15842868.4403492 5495063.52717435 10658494.8321262 1597723.95558547 18439092.7767796 693915.608514244 ;
-4938617.63788385 1770150.26203667 3552015.02297816 5495063.52717435 -1905431.6565515 -3696966.66609474 -556445.889290495 -6395440.49792196 -241701.988218099 ;
-9580867.29659882 3431284.086764 6888031.73340593 10658494.8321262 -3696966.66609474 -7167983.65268732 -1077627.53552742 -12402074.8481313 -468851.527481758 ;
-1640160.39791456 495695.981659611 1097285.87648895 1597723.95558547 -556445.889290495 -1077627.53552742 42436.4423290909 -1892585.94415359 9829.17048076255 ;
-16546506.832626 5938950.61774783 11908435.8473814 18439092.7767796 -6395440.49792196 -12402074.8481313 -1892585.94415359 -21451057.0582262 -821448.848767643 ;
-703744.778995006 217082.535858656 472266.490672735 693915.608514244 -241701.988218099 -468851.527481759 9829.17048076255 -821448.848767643 3414.96319097646 ;

it returns me the value -0.622 while Matlab and "http://matrix.reshish.com/determinant.php" return something about 3000.

Can someone explain/help me?
Thank you in advance.

Giacomo

**Comment by Giacomo1989ITA** [comment]
Also another online calculator ("https://matrixcalc.org/en/det.html") confirmed something about 3000.

**Comment by cdrnet** [comment]
What version are you using? Can you provide a repro?

Using v3.15 and your data I get the following results:

```
m.Determinant(): 2910.45503161593
m.LU().Determinant: 2910.45503161593
m.QR().Determinant: 2711.50100993881
m.Svd().Determinant: 2159.69032572403
```

Note that this matrix seems to be extremely ill-conditioned, according to the SVD decompoisition the condition number is in the area of 10^16, meaning that it is expected that you loose roughly 16 digits of precision on a decomposition.

**Comment by cdrnet** [comment]
Are you by chance using a native provider? I've recently become aware of a potential issue regarding the determinant when using the MKL native provider. Maybe this is be related.

**Comment by cdrnet** [comment]
Update: With `Intel MKL (x64; revision 11; MKL 2017.0)` I get:

```
3044.52875373839
3044.52875373839
2711.6202301308
2498.92919458303
```

**Comment by Giacomo1989ITA** [comment]
Hi, I'm using version 3.0, with MKL native provider.
Seeing discrepancy also passing through decompostion (as you did):
m.Determinant(): -0.62206832
m.LU().Determinant: -0.62206832
m.QR().Determinant: 0.36141234
m.Svd().Determinant: 0.69840893

**Comment by cdrnet** [comment]
Please upgrade to a newer version and try again (there should be no breaking changes within the same major version).

**Comment by Giacomo1989ITA** [comment]
Just updated the file "MathNet.Numerics.dll" to version 3.15 but still the same result.
Please note that other methods work correctly (for example Trace()) and for other simpler matrices the determinant calculation is ok.

**Comment by Giacomo1989ITA** [comment]
Tried updating also "MathNet.Numerics.MKL.dll" to last version (the one you mentioned) but nothing changed.

**Comment by cdrnet** [comment]
Thanks for trying. I wonder what is different in our setups then. This is the exact code I used, in LinqPad. Do you see a major difference to your code? Can you execute the same code on your side to confirm? (if you do not have LinqPad, just replace `Dump` with e.g. `Console.WriteLine`)

```
var data = @"-12604984.0868492 4607922.70918154 9144925.38542238 14245144.4847638 -4938617.63788385 -9580867.29659881 -1640160.39791456 -16546506.832626 -703744.778995006
4607922.70918154 -1637967.24867097 -3303925.85122784 -5103618.69084115 1770150.26203667 3431284.086764 495695.981659611 5938950.61774783 217082.535858656
9144925.38542238 -3303925.85122784 -6597834.9245516 -10242211.2619113 3552015.02297816 6888031.73340592 1097285.87648895 11908435.8473814 472266.490672735
14245144.4847638 -5103618.69084115 -10242211.2619113 -15842868.4403492 5495063.52717435 10658494.8321262 1597723.95558547 18439092.7767796 693915.608514244
-4938617.63788385 1770150.26203667 3552015.02297816 5495063.52717435 -1905431.6565515 -3696966.66609474 -556445.889290495 -6395440.49792196 -241701.988218099
-9580867.29659882 3431284.086764 6888031.73340593 10658494.8321262 -3696966.66609474 -7167983.65268732 -1077627.53552742 -12402074.8481313 -468851.527481758
-1640160.39791456 495695.981659611 1097285.87648895 1597723.95558547 -556445.889290495 -1077627.53552742 42436.4423290909 -1892585.94415359 9829.17048076255
-16546506.832626 5938950.61774783 11908435.8473814 18439092.7767796 -6395440.49792196 -12402074.8481313 -1892585.94415359 -21451057.0582262 -821448.848767643
-703744.778995006 217082.535858656 472266.490672735 693915.608514244 -241701.988218099 -468851.527481759 9829.17048076255 -821448.848767643 3414.96319097646";

var m = MathNet.Numerics.Data.Text.DelimitedReader.Read<double>(new StringReader(data), delimiter:" ");

Control.NativeProviderPath = @"...path to MKL provider dlls...";
Control.UseBestProviders();

m.Determinant().Dump();
m.LU().Determinant.Dump();
m.QR().Determinant.Dump();
m.Svd().Determinant.Dump();
m.Svd().ConditionNumber.Dump();
```

Which provides the following output:

```
3044.52875373839
3044.52875373839
2497.7966461037
2716.76727123143
1.16734443728568E+16
```

**Comment by Giacomo1989ITA** [comment]
Just a quick recap.

A0) using your code
A1) using "MathNet.Numerics.dll" v3.15
A2) using "MathNet.Numerics.Data.Text.dll" v3.2
A3) not using native provider (it was my actual configuration, my mistake saying I was using it)
->) 3044.5287537383851
->) 3044.5287537383851
->) 2716.5192827957976
->) 2715.80343876173
->) 11676198236329632.0

A0) using my code
A1) using "MathNet.Numerics.dll" v3.15
A2) using "MathNet.Numerics.Data.Text.dll" v3.2
A3) not using native provider
->) -0.27285325989707782
->) -0.27285325989707782
->) 0.28170511899743389
->) 0.258176543216848
->) 1.3384026870490422E+18

It's crazy because it's me having printed the matrix to file.
Following elements-per-elements matrices (including delta):
![image](https://cloud.githubusercontent.com/assets/24823808/21545946/b83849ac-cddb-11e6-9d39-7c6c72b3a41b.png)

Do you think that those little deltas could be responsible of the different results?

**Comment by Giacomo1989ITA** [comment]
Please insert this data in a proper tool (Excel) for inspection:

MATRIX1
-12604984.09
4607922.709
9144925.385
14245144.48
-4938617.638
-9580867.297
-1640160.398
-16546506.83
-703744.779
4607922.709
-1637967.249
-3303925.851
-5103618.691
1770150.262
3431284.087
495695.9817
5938950.618
217082.5359
9144925.385
-3303925.851
-6597834.925
-10242211.26
3552015.023
6888031.733
1097285.876
11908435.85
472266.4907
14245144.48
-5103618.691
-10242211.26
-15842868.44
5495063.527
10658494.83
1597723.956
18439092.78
693915.6085
-4938617.638
1770150.262
3552015.023
5495063.527
-1905431.657
-3696966.666
-556445.8893
-6395440.498
-241701.9882
-9580867.297
3431284.087
6888031.733
10658494.83
-3696966.666
-7167983.653
-1077627.536
-12402074.85
-468851.5275
-1640160.398
495695.9817
1097285.876
1597723.956
-556445.8893
-1077627.536
42436.44233
-1892585.944
9829.170481
-16546506.83
5938950.618
11908435.85
18439092.78
-6395440.498
-12402074.85
-1892585.944
-21451057.06
-821448.8488
-703744.779
217082.5359
472266.4907
693915.6085
-241701.9882
-468851.5275
9829.170481
-821448.8488
3414.963191

-------------------------

MATRIX2
-12604984.09
4607922.709
9144925.385
14245144.48
-4938617.638
-9580867.297
-1640160.398
-16546506.83
-703744.779
4607922.709
-1637967.249
-3303925.851
-5103618.691
1770150.262
3431284.087
495695.9817
5938950.618
217082.5359
9144925.385
-3303925.851
-6597834.925
-10242211.26
3552015.023
6888031.733
1097285.876
11908435.85
472266.4907
14245144.48
-5103618.691
-10242211.26
-15842868.44
5495063.527
10658494.83
1597723.956
18439092.78
693915.6085
-4938617.638
1770150.262
3552015.023
5495063.527
-1905431.657
-3696966.666
-556445.8893
-6395440.498
-241701.9882
-9580867.297
3431284.087
6888031.733
10658494.83
-3696966.666
-7167983.653
-1077627.536
-12402074.85
-468851.5275
-1640160.398
495695.9817
1097285.876
1597723.956
-556445.8893
-1077627.536
42436.44233
-1892585.944
9829.170481
-16546506.83
5938950.618
11908435.85
18439092.78
-6395440.498
-12402074.85
-1892585.944
-21451057.06
-821448.8488
-703744.779
217082.5359
472266.4907
693915.6085
-241701.9882
-468851.5275
9829.170481
-821448.8488
3414.963191

-------------------------

DELTAS
0
0
0
9.87202E-08
0
0
0
0
-1.04774E-09
0
0
0
0
0
0
0
0
9.8953E-10
0
0
0
0
0
1.02445E-08
1.00117E-08
1.00583E-07
9.8953E-10
9.87202E-08
0
0
0
1.02445E-08
0
0
0
9.31323E-10
0
0
0
1.02445E-08
-1.00117E-08
-9.77889E-09
-9.31323E-10
0
0
0
0
0
0
-9.77889E-09
0
0
0
-1.04774E-09
0
0
1.00117E-08
0
-9.31323E-10
0
1.01863E-10
0
0
0
0
1.00583E-07
0
0
0
0
0
-9.31323E-10
-1.04774E-09
0
9.8953E-10
9.31323E-10
0
0
0
-9.31323E-10
0

The dataare taken directly through VS QuickWatch

**Comment by Giacomo1989ITA** [comment]
Sorry, Excel truncated the values, please consider just those deltas.

**Comment by cdrnet** [comment]
Yes, they certainly can. That's exactly what a matrix being [ill-conditioned](https://en.wikipedia.org/wiki/Condition_number) means. A very small change in the input can have a huge impact on the output.

**Comment by Giacomo1989ITA** [comment]
Thanks for the reply, I agree with you about your explanation.
Regards
