### ISSUE TITLE
[Proposal] Drop .NET 3.5 support for next major release

### ISSUE THREAD

**Issue by iamcarbon** [mathnet/mathnet-numerics#475]
Would dropping .NET 3.5 support from the next major release adversely affect anyone?

This would lead to a dramatic simplification of the codebase, its testing, and allow us to take advantage of some pretty huge things that are coming to .NET (i.e. safe memory primitives).

**Comment by PawelTroka** [comment]
I'm all for this, I think NET40 is low enough. Just don't drop support for NET40 :)

**Comment by cdrnet** [comment]
To my understanding Unity still requires .Net 3.5 as of today.

**Comment by iamcarbon** [comment]
@cdrnet Looks like Unity has a branch with net4x support but there's no timetable for release. Worth reconsidering this when Unity gains proper support then.
