### ISSUE TITLE
MatlabWriter.Store generated .mat file corrupted

### ISSUE THREAD

**Issue by tcidy** [mathnet/mathnet-numerics#487]
I'm trying to pack the variable Z and Sr as a .mat file using the following code:

var Z = CreateMatrix.DenseOfColumns(new IEnumerable<double>[] { TFadjustedZ });
var Sr = CreateMatrix.DenseOfColumns(new Vector<Complex>[] { TFadjustedSr });
var matrices = new List<MatlabMatrix>();
matrices.Add(MatlabWriter.Pack(Z, "z"));
matrices.Add(MatlabWriter.Pack(Sr, "Sr"));
MatlabWriter.Store(sfd.FileName, matrices);

The .mat file I generated with the above code cannot be read by Matlab nor by MatlabReader. The issue might be caused by the presence of a corrupt zero-byte tag in the MAT-file.
System.OverflowException
It just happens sometimes, but I cannot duplicate the issue.
error message:
![image](https://cloud.githubusercontent.com/assets/22669459/25469390/c6d883c6-2ad0-11e7-8066-223758838476.png)

I read the corrupt .mat file byte by byte in Matlab using 'fread'. The 128 byte header looks good, and the followed 2 sets of tag+data portions are also normal. But then, at the end of the .mat file there are two abnormal int32 values:
![image](https://cloud.githubusercontent.com/assets/22669459/25469502/66e4bf92-2ad1-11e7-987d-a2c329b407cf.png)
I think these last 8 bytes cause the error
@Rickasaurus @cuda @jbowtie @cdrnet @iainsproat 
Thanks!

**Comment by pigrew** [comment]
This ended up being due to MatLabWriter.Store(...) using File.OpenWrite(). This command opens the file for editing. If the file exists, and the new data is shorter than the existing content, junk is left at the end of the file.

One solution would be to use the FileStream constructor directly, as described at [StackOverflow](http://stackoverflow.com/questions/3653132/file-openwrite-appends-instead-of-wiping-contents)

**Comment by cdrnet** [comment]
Good catch, thanks a lot for the analysis!

**Comment by cdrnet** [comment]
I expect this to be fixed in v3.2.1 of the data extensions. Please reopen if it happens again.

**Comment by tcidy** [comment]
Thanks a lot! FileStream works perfect.
