### ISSUE TITLE
PseudoInverse is not always precise

### ISSUE THREAD

**Issue by OronDF343** [mathnet/mathnet-numerics#492]
Given the following matrix a (double-precision):
```
a = [0.03, -0.01, 0
     -0.01, 0.01, 1
     0, 1, 0]
```

Let ap = the pseudo inverse of a
`
var ap = a.PseudoInverse();
`

The following comparison fails:
`
a.Equals(a * ap * a)
`

The error seems to be in the order of <1e-15

**Comment by jrynd** [comment]
How much precision would you expect, given the limitations of double-precision format? Even 3.0*(1.0/3.0) has an error of 10^-20 with double-precision, and a matrix inverse has many more operations.

**Comment by OronDF343** [comment]
It's not really an issue of accuracy but more of an issue of knowing what the accuracy is. I can use AlmostEqual and/or Math.Round to deal with this when comparing vectors, etc, but is there a way to determine what is the minimum parameter I can safely provide to those methods? (or basically, what is the accuracy of these operations? If you can provide a link to an article on this subject it'd be great)

**Comment by afraidOfMight** [comment]
IEEE 754 double-precision binary floating-point format gives 15–17 significant decimal digits precision. You get 16. 
If you need more, consider IEEE 754 quadruple-precision binary floating-point format, which uses 128bits and gives you 33 - 36 significant decimal digits precision. 
But let me tell you this: double-precision is enough.

**Comment by cdrnet** [comment]
Some background on the accuracy, stability and error bounds of the involved algorithms you can find in the [LAPACK reference](http://www.netlib.org/lapack/lug/node72.html). We only support single and double precision, but not quadruple-precision.

We compute the pseudo-inverse using an SVD decomposition, and for the tolerance of diagonal elements being non-zero we use `max(m,n) * L2-norm * epsilon (2^-53)`. Does that help?
