### ISSUE TITLE
Pre-relese (or release) of NuGet package with optimizatino

### ISSUE THREAD

**Issue by eriove** [mathnet/mathnet-numerics#498]
Would it be possible to create a pre-release or release including the optimization features?

**Comment by cdrnet** [comment]
Yes! I'll publish a pre-release.

**Comment by eriove** [comment]
Thanks!

**Comment by cdrnet** [comment]
I've just released [3.20.0-beta01](https://www.nuget.org/packages/MathNet.Numerics/3.20.0-beta01) including optimization as in current master. Thanks again!
