### ISSUE TITLE
Overloading Vector / Matrix functions in F#

### ISSUE THREAD

**Issue by ajwillshire** [mathnet/mathnet-numerics#502]
Might be doing this wrong (second day using F#!) but I have a method that applies to both vectors and matrices and would like to overload the function.

The F# compiler allows me to overload the function if I specify the arguments as DenseMatrix and DenseVector but not the generics, Vector<float>, Matrix<float>.

Is this expected and is there any way around it?

`//Vector Dirichlet Expectation
let dirichlet_expectation(input:Vector<float>) =
    let f1 x = SpecialFunctions.DiGamma(x)
    let rowSum = SpecialFunctions.DiGamma(input.Sum())
    let f2 x = x - rowSum
    input
    |> Vector.map f1
    |> Vector.map f2
    

//Matrix Dirichlet Expectation
let dirichlet_expectation_M(input:Matrix<float>) =
    input.EnumerateRows()
    |> Seq.map dirichlet_expectation
    |> DenseMatrix.OfRowVectors`

**Comment by cdrnet** [comment]
F# generally does not support function overloading (but allows method overloading), so you won't get around some way of distinction like e.g. the `_M` suffix if you want to define both functions within the same module.

Note that you still need to indicate the generic type parameter when specifying the type explicitly, although you can let if infer it. For example:

```
//Vector Dirichlet Expectation
let dirichlet_expectation(input:Vector<_>) =   // compiler infers it as Vector<float>
    let f1 x = SpecialFunctions.DiGamma(x)
    let rowSum = SpecialFunctions.DiGamma(input.Sum())
    let f2 x = x - rowSum
    input
    |> Vector.map f1
    |> Vector.map f2
```
