### ISSUE TITLE
Matrix Pointwise Functions in F#

### ISSUE THREAD

**Issue by ajwillshire** [mathnet/mathnet-numerics#503]
If I have a Matrix in F# and I want to create a copy with a Pointwise function applied, I assumed that I could do
```
let expELogTheta = eLogTheta.PointwiseExp
```
but this has return type Unit. I think I can do
```
let expELogTheta = eLogTheta |> Matrix.map (fun z -> exp(z))
```
instead to give me what I want.

However, given that the Pointwise methods are Functions in VB and C# with the return value Matrix(Of T) it seems inconsistent not to have the same behaviour. Unless I'm missing something (highly likely).

**Comment by cdrnet** [comment]
In F# you're supposed to be able to use the built-in `exp` funtion:

    let expELogTheta = exp eLogTheta

For other pointwise operations there are typically special operators available, e.g.

    let m1 = a .* b

**Comment by cdrnet** [comment]
Ah, the method `PointwiseExp` should work as well, but since it has no arguments you need to pass "unit" (empty parentheses) for it to actually execute, i.e.

    let expELogTheta = eLogTheta.PointwiseExp ()

**Comment by ajwillshire** [comment]
Thanks - will get the hang of this eventually!
