### ISSUE TITLE
Error using InverseCumulativeDistribution function in Silverlight

### ISSUE THREAD

**Issue by jaencalo** [mathnet/mathnet-numerics#505]
Hi : I am testing the library on silverlight 5.0 to use Students Test... when I try to get the InverseCumulative Distribution using 0.0 as location, 1.0 as scale, 5.0 as degrees and 0.4 as value the function throw an error : 0x800a139e - Error en tiempo de ejecución de JavaScript: Unhandled Error in Silverlight Application The algorithm has failed, exceeded the number of iterations allowed or there is no root within the provided bounds.   en MathNet.Numerics.RootFinding.Brent.FindRoot(Func`2 f, Double lowerBound, Double upperBound, Double accuracy, Int32 maxIterations)

this is my code : 
            StudentT x = new StudentT(0.0, 1.0, 5.0);
            double rta = x.InverseCumulativeDistribution(0.4);

can you check this issue... thanks in advance, 

Javier Carreño, from Bogota, Colombia

**Comment by jaencalo** [comment]
Additionally, I tested the same code on a winforms application (referencing main MathNet.Numerics dll, not silverlight dll), and the function worked fine...

**Comment by cdrnet** [comment]
What version of the package are you using? We've increased the number of iterations in v3.20.0, so if you use an older version, upgrading to v3.20 could help.

**Comment by jaencalo** [comment]
Christoph, thanks a lot for your fast response... after more tests, I found an error in my code... I was always sending 1.0 to value parameter of InverseCumulativeFunction and it generated the error... the function works fine right now for me, and thanks a lot for your help... with your response, I downloaded 3.19 version, tested it, and works too... thanks again... awesome work !!!

Javier Carreño, from Bogota, Colombia

**Comment by cdrnet** [comment]
Great, thanks for the update!
