### ISSUE TITLE
Issue with Matrix hashCode implementation

### ISSUE THREAD

**Issue by sharadkjaiswal** [mathnet/mathnet-numerics#520]
There seems to be typo error in [hashcode implementation for MatrixStorage](https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/LinearAlgebra/Storage/MatrixStorage.cs#L194). We should be using **%** operator instead of **/** operator. Otherwise, row could go out of bound in some cases such as 3x12 matrix.

**Comment by cdrnet** [comment]
This has been fixed in #535. Thanks for reporting!
