### ISSUE TITLE
Doing Matrix instantiation programatically

### ISSUE THREAD

**Issue by ooples** [mathnet/mathnet-numerics#529]
I'm new to this library and I'm trying to figure out how to create a matrix programatically like the below code

Matrix<double> matrix = new Matrix<double>();
matrix.Add(new List<double> list1());
matrix.Add(new List<double> list2());

Does anyone know how to do something like this?

**Comment by cdrnet** [comment]
See cross-post: https://stackoverflow.com/questions/47124688/doing-matrixdouble-instantiation-programatically-math-net-c-sharp-library
