### ISSUE TITLE
any plans to update to the latest intel MKL (v2018)?

### ISSUE THREAD

**Issue by jaybert** [mathnet/mathnet-numerics#530]
Looks like 2018 has been released

https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2018-release-notes

And it is optimized for the latest processors that amazon just released (C5) per here: https://aws.amazon.com/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/

Thanks!

**Comment by cdrnet** [comment]
I have some issues with the 2018 Intel tooling setup in VS2017 on my machine, but I've had another look at it recently and managed to work around. So yes, I intent to release a new build soon.

**Comment by cdrnet** [comment]
Version 2.3 (revision 12) is built against Intel MKL 2018.0 Update 1.
