### ISSUE TITLE
Evaluation of Coth(z)

### ISSUE THREAD

**Issue by diluculo** [mathnet/mathnet-numerics#539]
In the `MathNet.Symbolics`, I have found `Coth(z)` function gives incorrect value. The problem is the wrong sign of imaginary part:

> coth(1 + Expression.I) |> Approximate.approximate;;
val it : Expression = 0.868014142895925 + 0.217621561854403*j

> cosh(1 + Expression.I) / sinh(1 + Expression.I) |> Approximate.approximate;;
val it : Expression = 0.868014142895925 - 0.217621561854403*j

Actually it is a bug in `Coth(z)` function of `MathNet.Numerics`. Its last line should be updated as follows:

```
public static Complex Coth(this Complex value)
{
      ...
      //return new Complex(sinhr * Cosh(value.Real) / denom, sini * Cos(value.Imaginary) / denom);
      return new Complex(sinhr * Cosh(value.Real) / denom, - sini * Cos(value.Imaginary) / denom);
}
```

**Comment by cdrnet** [comment]
For reference, according to Mathematica:

![coth](https://user-images.githubusercontent.com/47147/34727892-8d25dc5c-f558-11e7-9a6d-f7568c32e9b7.png)

**Comment by diluculo** [comment]
Yes, so we can simply prove that imaginary part of `cosh(x + j y)` can be written as 
`sin(2*y)/(cos(2*y) - cosh(2*x)) = - sin(y)*cos(y)/(sin(y)^2 + sinh(x)^2)` 

by using
- `sin(2*y) = 2*sin(y)*cos(y)`
- `cos(2*y) = cos(y)^2 - sin(y)^2 = 1 - 2*sin(y)^2`
- `cosh(2*x) = cosh(x)^2 + sinh(x)^2 = 1 + 2*sinh(x)^2`

**Comment by cdrnet** [comment]
Excellent, thanks! I'll provide a fix.

**Comment by cdrnet** [comment]
Fixed in master. Thanks again for reporting.

To be released as part of v4.0.0-beta03. Let me know if there is a need to backport to v3 as well.

**Comment by diluculo** [comment]
@cdrnet Many thanks for very quick update.

Just now, I find another problem: `Coth(500 + 500 j)` gives `0`. It should return `1`. It happens in Tanh(z), too. Inside the code, you can watch `sinhr = 7.012E+216 != oo`, so `denom = oo`. Please check if `denom` or `sinhr * sinhr` is `Infinity` as follows.:

```
        public static Complex Coth(this Complex value)
        {
            ...
            if (double.IsInfinity(sinhr) || double.IsInfinity(sinhr * sinhr))
            {
                return new Complex(Math.Sign(sinhr), 0.0);
            }
            ...
        }
```

One more, how to apply new `Numerics` release to `Symbolics`?

**Comment by cdrnet** [comment]
Thanks. I've reopened the issue to keep track of it.

Regarding updating Numerics in Symbolics: You can update it using `./paket.sh update MathNet.Numerics` (or `.paket\paket.exe update MathNet.Numerics`), but that will only update to the latest release. Unfortunately the fix is only in a pre-release so far (I have not yet back-ported to v3 and am not yet ready to release v4), so we need to allow pre-releases explicitly by adding appending the string ` prerelease` to the Numerics entry in the paket.dependencies file first. But I can take care of it.

**Comment by diluculo** [comment]
With the help of Google, I found [Kahan's paper](https://people.freebsd.org/~das/kahan86branch.pdf), describing how to calculate `Tanh(z)`. This algorithm is found in many math libraries such as [Numpy](https://github.com/numpy/numpy/blob/master/numpy/core/src/npymath/npy_math_complex.c.src).

I expanded it to `Coth(z)`, `Tan(z)`, and `Cot(z)`. Please see this:
[Tanh Coth Tan Cot functions with Kahan Algorithm.pdf](https://github.com/mathnet/mathnet-numerics/files/1625949/Tanh.Coth.Tan.Cot.functions.with.Kahan.Algorithm.pdf)

Modified functions (in my test project not yet in Numerics) give right values for large complex arguments. Next week, I will check more and send PR.

**Comment by diluculo** [comment]
Returns of hyperbolic functions are summarized as follows:

z   = 512 + 32 j | Numerics   v4.0.0-beta04 | Correct   Value
-- | -- | --
Tanh(z) | 0 + 0 j | 1 + 3.52598650243738e-445 j
Csch(z) | NaN + NaN j | 7.30361056703505e-223 - 4.82773070945482e-223 j
Sech(z) | NaN + NaN j | 7.30361056703505e-223 - 4.82773070945482e-223 j
Coth(z) | 0 + 0 j | 1 - 3.52598650243738e-445 j

Other (hyperbolic) trigonometric functions gives correct values. We have to update Csch(z) and Sech(z), too. I updated above pdf file(Tanh Coth...pdf).

**Comment by diluculo** [comment]
x = 1.7976931348623157E+308 | Numerics | Correct
-----------------------------------|------------|----------
Asinh(x) | Infinity | 710.47586007394394204
Acosh(x) | Infinity | 710.47586007394394204

For the functions, we can apply an approximation: sqrt(x*x + 1) ~= x for x is huge.

**Comment by diluculo** [comment]
FYI, implemented algorithms of the commits are summarized in [Hyperbolic trigonometric functions.pdf](https://github.com/mathnet/mathnet-numerics/files/1641367/Hyperbolic.trigonometric.functions.pdf).

**Comment by cdrnet** [comment]
Thanks a lot also for putting the document together - appreciated!

**Comment by diluculo** [comment]
Glad to have a chance to contribute to this great product. Thanks.
