### ISSUE TITLE
MKL in Docker seems not working

### ISSUE THREAD

**Issue by arthurvb** [mathnet/mathnet-numerics#562]
Dear fellow coders,

Today I tried to get MKL working in the ``microsoft/aspnetcore:2.0`` Docker. 
For this I downloaded the compiled MKL from https://www.nuget.org/packages/MathNet.Numerics.MKL.Linux/ . 
The setting ``MathNet.Numerics.Control.NativeProviderPath`` points to a directory where both the ``libiomp5.so`` as well as ``MathNet.Numerics.MKL.dll`` are located. 

The first error I get is ``Unable to load DLL 'libdl.so'``. This is solved by doing ``ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so`` as mentioned in https://github.com/dotnet/corefx/issues/25102 .

However when this error is fixed, calling ``MathNet.Numerics.Control.UseNativeMKL();`` gives me the following error 

```
System.NotSupportedException: MKL Native Provider not found. ---> System.DllNotFoundException: Unable to load DLL 'MathNet.Numerics.MKL.dll': The specified module or one of its dependencies could not be found.
container_1  |  (Exception from HRESULT: 0x8007007E)
container_1  |  at MathNet.Numerics.Providers.Common.Mkl.SafeNativeMethods.query_capability(Int32 capability)
```

Although this dll is present in the nativeproviderpath..

Does any of you have pointers how this could be solved, or how I can help to solve this?

Thank you in advance, the library is much appreciated!

Best regards,

Arthur

**Comment by arthurvb** [comment]
Ok, copying the files to a location as described in https://stackoverflow.com/questions/31351343/mono-mathnet-mkl-nativer-provider-not-found at least replaced the error by:

```
Could not load MKL: System.NotSupportedException: MKL Native Provider revision r9 is too old. Consider upgrading to a newer version. Revision r11 and newer are supported.
```

**Comment by arthurvb** [comment]
OK, perfect!, looking at the code it seems that only the fourier transform MKL will not be loaded but for linear algebra it will use the latest version; issue solved, thank you.
Although it might be relevant to one time have the latest MKL providers for Linux.

**Comment by SarcoZ** [comment]
Could not load MKL: System.NotSupportedException: MKL Native Provider revision r9 is too old. Consider upgrading to a newer version. Revision r11 and newer are supported.

how resolve this issues?

**Comment by SarcoZ** [comment]
@arthurvb 

Could not load MKL: System.NotSupportedException: MKL Native Provider revision r9 is too old. Consider upgrading to a newer version. Revision r11 and newer are supported.

how resolve this issues?

**Comment by OneNeoEno** [comment]
@SarcoZ  This is probably way too late for you, but will hopefully be useful to anyone else searching for this error message.

If you're wanting to use Fourier Transforms, you're probably SOL, I can't see any way to make that work.

If all you want is the linear algebra, you probably got this error message by calling MathNet.Numerics.Control.UseNativeMKL(). Behind the scenes, this will then go call UseNativeMKL on both the linear algebra and the fourier transform controls, and the latter appears to not work on Linux.

If you instead call MathNet.Numerics.Providers.LinearAlgebra.LinearAlgebraControl.UseNativeMKL(), you should be good.
