### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by FoggyFinder** [mathnet/mathnet-numerics#579]
I try to use MathNet.Numerics with UWP. 

Note, all code related to MathNet defined in separate netstandard2.0 library. If add MathNet directly to UWP project without netdtandard library as an additional layer it works fine.

When it builds in relise mode I got the follow warnings:

```
warning MCG0007: Unresolved P/Invoke method 'kernel32!LoadLibraryEx' for method 'System.IntPtr MathNet.Numerics.Providers.Common.NativeProviderLoader.WindowsLoader.LoadLibraryEx(System.String, System.IntPtr, System.UInt32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
warning MCG0007: Unresolved P/Invoke method 'libdl.so!dlopen' for method 'System.IntPtr MathNet.Numerics.Providers.Common.NativeProviderLoader.UnixLoader.dlopen(System.String, System.Int32)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
```

As a result app closing immediately.

Am I missing something or right now it's impossible to use library this way?

**Comment by NilesDavis** [comment]
OK, after fixing some related errors in my code I also ran into the same problem with the exact same warnings. Is there any chance to solve this?

**Comment by NilesDavis** [comment]
@FoggyFinder did you have any success with this issue? Or did you just take the old 3.x versions?

**Comment by cdrnet** [comment]
The code mentioned by the warning should be never executed if you call `Control.UseManaged();` before any usage of Math.NET Numerics to disable native providers entirely. With this call, does the app still close immediately? Is there any error/reason reported when it closes?

**Comment by cdrnet** [comment]
Related discussion: https://discuss.mathdotnet.com/t/uwp-support-with-netcore-2/707

**Comment by SuperJMN** [comment]
I have tried to certificate a Windows Universal Application using Math.NET Numerics and it has been rejected due to this:

> Error Found: The supported APIs test detected the following errors
> * API c_axpy in mathnet.numerics.cuda.dll is not supported for this application type. SuppaFlight.UWP.dll calls this API.
> * API c_cholesky_factor in mathnet.numerics.cuda.dll is not supported for this application type. SuppaFlight.UWP.dll calls this API.
> * API c_cholesky_solve in mathnet.numerics.cuda.dll is not supported for this application type. SuppaFlight.UWP.dll calls this API.
> * API c_cholesky_solve_factored in mathnet.numerics.cuda.dll is not supported for this application type. SuppaFlight.UWP.dll calls this API.
> * API c_dot_product in mathnet.numerics.cuda.dll is not supported for this application type. SuppaFlight.UWP.dll calls this API.

Please, make it compatible.

**Comment by nige77** [comment]
This might help whoever reads this. I have been having a problem deploying an Universal Application in release mode on a Raspberry Pi. The error is that the application can't be started. It also says a DLL is missing. I have narrowed this problem down to the Math.Net library. I also see 'Unresolved P/Invoke method 'libdl.so!dlopen''. Building a new application with only the Math.Net library installed (NuGet) the problem still exists. I have gone backwards from Version 4.7 to 4.0 without any change. However  at version 3.20.2 all is working fine.

**Comment by gregorijk** [comment]
I have run into the same issue when using MathNet 4.7 for UWP app. The app crashes on runtime when built in Release mode with "Compile with .NET Native tool chain" enabled. It reports "missing dll". Everything works fine with MathNet 3.x versions.
The build with 4.7 works fine if changing the min Target version from Fall Creators Update (16299) to Creators Update (15063). Unfortunately I need to run the app with Fall Creators Update so I'm stuck with MathNet 3.x version.

**Comment by myokeeh** [comment]
Also running into this. Going back to 3.20.2 for the meantime.

**Comment by omghb** [comment]
I'm running into the same issue.

**Comment by andygikling** [comment]
Similar issue here.  Can't submit my app which uses MathNET.New

The Windows App Certification Kit 10.0.18362.1 gives supported API failures.

Supported APIs
Error Found: The supported APIs test detected the following errors:
API c_axpy in mathnet.numerics.cuda.dll is not supported for this application type. MathNet.Numerics.dll calls this API.

With about 200 other of the same violations.  It seems MathNET doesn't currently support UWP/Windows Store because of these API calls.  

Is there a way to totally disable, for example, Cuda support in the library?

**Comment by songshizhao** [comment]
> This might help whoever reads this. I have been having a problem deploying an Universal Application in release mode on a Raspberry Pi. The error is that the application can't be started. It also says a DLL is missing. I have narrowed this problem down to the Math.Net library. I also see 'Unresolved P/Invoke method 'libdl.so!dlopen''. Building a new application with only the Math.Net library installed (NuGet) the problem still exists. I have gone backwards from Version 4.7 to 4.0 without any change. However at version 3.20.2 all is working fine.

 I change my package from 4.0->3.20.20, it worked. This message is useful! Thank you !

**Comment by myokeeh** [comment]
Could the answer in the link below also work for the underlying issue here? https://stackoverflow.com/questions/59378156/il2cpp-compiled-uwp-app-using-windows-system-dlls-on-arm/59402735#59402735

**Comment by sastorer-ms** [comment]
> > This might help whoever reads this. I have been having a problem deploying an Universal Application in release mode on a Raspberry Pi. The error is that the application can't be started. It also says a DLL is missing. I have narrowed this problem down to the Math.Net library. I also see 'Unresolved P/Invoke method 'libdl.so!dlopen''. Building a new application with only the Math.Net library installed (NuGet) the problem still exists. I have gone backwards from Version 4.7 to 4.0 without any change. However at version 3.20.2 all is working fine.
> 
> I change my package from 4.0->3.20.20, it worked. This message is useful! Thank you !

This issue is still a problem! Rolling back the version worked for me as well.

**Comment by myokeeh** [comment]
So, this appears to work. I'm not sure if I tried it before or if I tried it AND didn't work before. Changed 4.8.1 to 4.15.0 in the csproj modification below and it runs and passes Partner Center certification.

> I'm running into the same issue: "missing dll" when ".NET Native tool chain" is used.
> 
> _Workaround:_ Use the `.NET Standard 1.3` version of `MathNet.Numerics` as it does not include the native providers.
> 
> ```
> <ItemGroup>
>   <PackageReference Include="MathNet.Numerics" Version="4.8.1" ExcludeAssets="All" />
> </ItemGroup>
> <ItemGroup>
>   <Reference Include="MathNet.Numerics.Ref" HintPath="$(NuGetPackageRoot)mathnet.numerics\4.8.1\lib\netstandard1.3\MathNet.Numerics.dll" />
> </ItemGroup>
> ```

**Comment by groovykool** [comment]
What is the status of this issue?

**Comment by cdrnet** [comment]
To my understanding this should finally be resolved in the v5 prereleases, since they no longer contain any p/invoke at all (they have been moved out to separate provider nuget packages)

**Comment by cdrnet** [comment]
Closing this since this should be resolved in v5 - in fact, this problem was one of the drivers for the new native provider integration approach, one of the main aspects of v5. Please comment/reopen if there are still issues.
