### ISSUE TITLE
Not working using .Net Native toolchain

### ISSUE THREAD

**Issue by NilesDavis** [mathnet/mathnet-numerics#594]
I am building an app which should be installed via the store which forces me to compile it using the .Net Native toolchain. If this checkbox is activated in a UWP app, it is possible to build, but not possible to start it. It always crashes during startup with Code -1073741515 (0xc0000135).
Why is it like that?

**Comment by NilesDavis** [comment]
this is eventually connected to #579

**Comment by NilesDavis** [comment]
OK, mathnet was not the problem with this. I had another dependency to the Behaviours SDK and this seems to be totally buggy. As I got not real hint how ti came to the crashed, even with native debugging, I accidently remove the Behaviours SDK and exchanged it with Microsoft.Xaml.Behaviors.Uwp.Managed. Finally it all worked perfectly!

**Comment by cdrnet** [comment]
Thanks for the update!
