### ISSUE TITLE
can i read matlab cell array by using matlabreader?

### ISSUE THREAD

**Issue by ruruoruo** [mathnet/mathnet-numerics#606]
My data source just like this
![image](https://user-images.githubusercontent.com/42052208/48750370-b8e63680-ecb9-11e8-9901-37d61b1baa09.png)
![image](https://user-images.githubusercontent.com/42052208/48750411-e7641180-ecb9-11e8-9f19-3c2bcf167cf9.png)
and my code is 
![image](https://user-images.githubusercontent.com/42052208/48750511-61949600-ecba-11e8-8829-47a012a320ff.png)
But it throws an exception System.NotSupportedException.
What should i do?

**Comment by eriove** [comment]
If I remember correctly only scalars, matrices and vectors are supported, and then in an old format. The new Matlab file formats are more complicated to read.
