### ISSUE TITLE
Any plan to take advantage of System.Memory

### ISSUE THREAD

**Issue by hanabi1224** [mathnet/mathnet-numerics#610]
Read about that new System.Span and System.Memory brings huge performance gain in .net core, just curious if those would benefit the array operations here?

**Comment by Apollo3zehn** [comment]
Support for Span<T> would be really great and would save me a huge number of copy operations. Implementation should'nt be too difficult. In my case I am interested in functions like
 
- ArrayStatistics.Mean
- ArrayStatistics.Minimum
- ArrayStatistics.Maximum
- ArrayStatistics.StandardDeviation
- ArrayStatistics.RootMeanSquare

I am downsampling data by dividing the original dataset into pieces that are then processed by one of these methods. But for each piece I need to create a new array, with Span<T>``` this won't be required anymore.

**Comment by cdrnet** [comment]
Yes, this is on the roadmap!

**Comment by aaronhudon** [comment]
Suggesting `MathNet.Numerics.Fit` functions be considered for `Span` support.

**Comment by oscarvarto** [comment]
I am also interested in this topic. @cdrnet, could you please elaborate on the roadmap you mentioned?

**Comment by RossMMason** [comment]
Any update on this?
