### ISSUE TITLE
Compute right-tail probability at point x of Chi-squared distribution

### ISSUE THREAD

**Issue by VJalili** [mathnet/mathnet-numerics#616]
I would like to compute the right-tail probability at point `x` of a chi-squared distribution. 

For comparison; currently I am using the following functions in Excel and R: 

```csharp
// Excel: 
=CHISQ.DIST.RT(100, 6)
// result: 2.5093E-19

// R:
> pchisq(100, 6, lower.tail = FALSE)
[1] 2.509304e-19
```

I don't see a function for right-tail probability in [ChiSquared](https://github.com/mathnet/mathnet-numerics/blob/7e450663689d8555de50caf5d39ec744ccf1c733/src/Numerics/Distributions/ChiSquared.cs#L43) class; closest functions I see are [`CumulativeDistribution`](https://github.com/mathnet/mathnet-numerics/blob/7e450663689d8555de50caf5d39ec744ccf1c733/src/Numerics/Distributions/ChiSquared.cs#L215) and [`Density`](https://github.com/mathnet/mathnet-numerics/blob/7e450663689d8555de50caf5d39ec744ccf1c733/src/Numerics/Distributions/ChiSquared.cs#L193). Any idea on how I can compute right-tail probability?

**Comment by cdrnet** [comment]
You can compute the right-tail from the left-tail, i.e. `1.0 - ChiSquared.CDF(6, 100)`.

Unfortunately this approach reduces the precision to roughtly `1.11e-16` when the CDF gets close to one. In your example the CDF will become `1.0` and the difference will thus be `0.0`. I guess this is the main reason both Excel and R provide separate implementations for this use case.

**Comment by VJalili** [comment]
That's right, I was getting `1.0`, and I thought there might be different function I need to use. Thank you for clarification. 

I am using `mathnet-numerics` for a genomics application ([ChIP-seq](https://en.wikipedia.org/wiki/ChIP-sequencing) to be specific) where `x>100` is fairly common. So, I was wondering if there is any plan to support such use cases.

**Comment by cdrnet** [comment]
Interesting, thanks!

Yes, we better do that. For Chi-Squared it seems we already have the necessary special functions available, so it should be straight forward to implement: `SpecialFunctions.GammaUpperRegularized(a/2.0,x/2.0)` (returns `2.50930355220106E-19` for a=6 and x=100).

**Comment by VJalili** [comment]
Thank you! 
The following works fine for me:

```csharp
using MathNet.Numerics;
right-tail-probability = SpecialFunctions.GammaUpperRegularized(df / 2.0, x / 2.0);
```

Maybe we can interface this better from the `ChiSquared` class.

**Comment by cdrnet** [comment]
What about the following two (we usually provide both static and instance variants for convenience)?

- `public static double RightCDF(double freedom, double x)` (similar to static InvCDF)
- `public double RightSidedCumulativeDistribution(double x)` (similar to InverseCumulativeDistribution)

**Comment by VJalili** [comment]
LGTM. Thank you.
