### ISSUE TITLE
Unexpected result in SpecialFunctions.BetaRegularized

### ISSUE THREAD

**Issue by DrWD-1** [mathnet/mathnet-numerics#623]
With both build 4.7.0 and earlier builds, SpecialFunctions.BetaRegularized(0.022685985, 14382.53378, 0.999999805) returns 1 instead of about 0.000653; the latter can be obtained from R (qbeta(0.999999805, 0.022685985, 14382.53378)) or from Excel (BETA.INV(0.999999805; 0.022685985; 14382.53378)).

**Comment by aptus-jaime** [comment]
I just checked the value in Mathematica and the output for the input numbers was ~1 to a high degree of accuracy.  Also, are you sure "qbeta" is what you need to compute?  According to this:

https://stat.ethz.ch/R-manual/R-patched/library/stats/html/Beta.html

it is "pbeta" which corresponds to the regularized beta function.

**Comment by jaime-varela** [comment]
I just checked Mathematica and the regularized beta was approximately 1 there as well.  Are you sure qbeta is the correct function?  According to this:

https://stat.ethz.ch/R-manual/R-patched/library/stats/html/Beta.html

pbeta is the function which corresponds to the regularized beta function (I am not too familiar with R).

**Comment by DrWD-1** [comment]
You're right, sorry for the confusion.
