### ISSUE TITLE
Multiply for managed provider incorrect when target matrix is this

### ISSUE THREAD

**Issue by rca22** [mathnet/mathnet-numerics#626]
If we examine the implementation of this.Multiply at 
https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/LinearAlgebra/Double/Matrix.cs line 197 then it can be seen that 
a.Multiply(b,b) or a.Multiply(b,a) will result in an incorrect matrix being calculated, because the destination is the same as the source, and writing the first element in the destination corrupts subequent calculations.
This could be fixed by a check that the output argument is not pointing to the same matrix as one of the two inputs.
This does not seem to cause problems in practice when using the MKL linear algebra provider; there must be an implicit copy of data somewhere to prevent it.

**Comment by cdrnet** [comment]
This is supposed to be handled by https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/LinearAlgebra/Matrix.Arithmetic.cs#L743, which is supposed to be the only caller of DoMultiply. Is there another caller that I'm missing here?

**Comment by rca22** [comment]
Hi Christoph,

Thanks for the email. I think that I might have misunderstood what is happening here. If these checks are applied at a higher level and then the different implementations of DoMultiply are plugged in then this would explain the observations I've made in my code. Let me dig into that and get back to you ASAP.

Thanks,

Richard

________________________________

**Comment by rca22** [comment]
Hi Christoph,

I've confirmed that this is the case and I'm happy to close this issue. Thanks for the assistance.

Richard
