### ISSUE TITLE
NelderMeadSimplex Does Not Always Return Best Evaluated Point

### ISSUE THREAD

**Issue by EricScottSalem** [mathnet/mathnet-numerics#632]
If TryToScaleSimplex(-1.0,...) (line 146) results in a converged state, and then TryToScaleSimplex(2.0,...) (line 151) or TryToScaleSimplex(0.5,...) (line 159) is immediately run, the ObjectiveFunction will contain the point and value states of the latter, which can be worse than the previously established vertices.
For a discontinuous function or a function with a steep valley, this can result in a significantly erroneous result. 

For example:

```
 var result = NelderMeadSimplex.Minimum(ObjectiveFunction.Value(
                x =>
                {
                    if (x[0] < 0.0 || x[0] >= 1) return Double.MaxValue;
                    return Math.Pow(x[0], 6.0);
                }), 
                Vector<double>.Build.Dense(new[] { 0.5 }), 0.0000000000000000001);
Console.WriteLine($"{result.MinimizingPoint[0]} {result.FunctionInfoAtMinimum.Value} {result.Iterations}");

Output:
-4.44089209850063E-16 1.79769313486232E+308 64
```

By adding a final 
`objectiveFunction.EvaluateAt(vertices[errorProfile.LowestIndex]);`
prior to instantiating the MinimizationResult, the objectiveFunction will be set to the proper state, and the MinimizationResult will be initialized with the proper values.  
The code above then properly outputs 
`6.10351562455592E-06 5.1698788261995E-32 64`

**Comment by EricScottSalem** [comment]
[PR](https://github.com/mathnet/mathnet-numerics/pull/633) to fix.

**Comment by cdrnet** [comment]
Thanks for the analysis and the PR!

**Comment by EricScottSalem** [comment]
Thanks!

**Comment by eriove** [comment]
@EricScottSalem: Since you are using Nelder Mead Simplex. Beware of [this](https://github.com/mathnet/mathnet-numerics/issues/501) bug, essentially it fails to find the minimum for completely symmetrical functions. Since you solved this problem, perhaps you are aware of how to solve #501 as well?

**Comment by EricScottSalem** [comment]
@eriove Hi, I am aware of that problem (I hesitate to call it a bug as I believe the code implements the original Nelder Mead Simplex algo accurately).  
I am not an expert in this area, but I believe this is something of a known problem and can be found discussed in various literature; Googling "Nelder Mead convergence" produces many interesting hits.
I am not quite sure which of these would solve this (and all other) problems.
A dirty fix, in this case, is to perturb the simplex one more time after convergence to ensure it remains converged.  I hesitate to put up a PR to do this as it has no real theoretical basis, nor any paper I can cite, and it's ugly.
That being said, the following code gets 1 + x^2 to converge:
```
               if (HasConverged(convergenceTolerance, errorProfile, errorValues))
                {
                    numTimesHasConverged++;
                }
                else
                {
                    numTimesHasConverged = 0;
                }

                if (numTimesHasConverged == 2)
                {
                    exitCondition = ExitCondition.Converged;
                    break;
                }
```

**Comment by eriove** [comment]
Thanks, @EricScottSalem

@cdrnet : Would you accept a pull request with this change? In that case I'll add some tests and make the change. It would make the results much more intuitive even if it isn't strictly correct.

**Comment by EricScottSalem** [comment]
@eriove @cdrnet I've consulted with some colleagues who also think this change is would be beneficial and think I was being overly cautious with my initial hesitation.
