### ISSUE TITLE
TryFindRoot allows negative accuracy which always fails to find a root

### ISSUE THREAD

**Issue by andrewimcclement** [mathnet/mathnet-numerics#642]
Brent.TryFindRoot and Bisection.TryFindRoot both allow a caller to pass in a negative value for the accuracy (arguably 0 could also be problematic, but should probably be permissible). However, the implementation of each means that it never considers itself to be within the requested accuracy, therefore always returns false.

Given that an accuracy is an absolute value, ideally the caller is either required to pass in a non-negative/positive value (i.e. throw ArgumentException(nameof(accuracy)) if a negative value is passed in) or accuracy should be converted to its absolute value.

Whichever solution is chosen should also be noted in documentation for the accuracy parameter on the TryFindRoots method, so users know what to expect.

I found this using MathNet.Numerics version 3.19.0 nuget package, from reading the code the issue is still present in master.

**Comment by cdrnet** [comment]
In what use case would one provide a negative accuracy parameter? What would be the desired intention of this? One could argue that a negative accuracy is impossible to reach, so always failing to find roots would be the expected result.

But I agree that either way this should at least be explicitly documented.

**Comment by RyanGrange** [comment]
Since the accuracy is being checked against an absolute value already it seems to make the most sense to me to test the absolute value of accuracy and accuracy is usually written as +/-N which returns the same set of numbers for -N as +N.

**Comment by RyanGrange** [comment]
I wish I understood roots better, but I'm way too far past my math classes.
I think if accuracy is expected to be an absolute value to mathematicians, then throwing an error on negatives makes sense.
If the accuracy checks should be for less-than or equal to the accuracy, then allowing 0 makes sense.  Right now the formulae are written with Math.Abs(fx) < accuracy, so 0 is impossible.
If anyone knows the rules for how this is supposed to work, I'll be glad to put in a PR updating the code and the XMLDoc to match.

**Comment by RyanGrange** [comment]
I spoke with a data scientist I know and this is what he said...
"I don't think I've ever used a root finding implementation that didn't error when tol <= 0.  Zero as a tolerance can't happen except in the most ridiculous of trivial circumstances."
"Since Brent's method uses quadratic approximations it's probably more sensitive to the tolerance being too small, whereas bisection will be less sensitive... but once you get near that epsilon value then numerical errors start to swamp out your real goal."
"But yeah I'd error out on zero or negative tolerance."
I'll credit him by name later if he approves it.

**Comment by RyanGrange** [comment]
https://github.com/mathnet/mathnet-numerics/pull/697 created to fix Brent and Bisection invalid accuracy values.

**Comment by andrewimcclement** [comment]
The PR looks good to me - throwing seemed the better solution to me as well.

**Comment by cdrnet** [comment]
PR merged - thanks!
