### ISSUE TITLE
BfgsBMinimizer fails to converge on simple boundary solution

### ISSUE THREAD

**Issue by tmct** [mathnet/mathnet-numerics#658]
We've seen this optimisation method fail to converge on many examples, including the very simple example I've created a failing test for here: https://github.com/tmct/mathnet-numerics/commit/1f8d0536d388e47e2b8f9ccf91f21e6870ea0f5a (second test fails to converge)

This just tries to minimise `x^2 + y^2` over [1,2] x [1,2], and it feels like it should arrive at [1,1] fairly quickly from that...

I may try to fix this and create a PR.

**Comment by tmct** [comment]
Just thought I'd check: L-BFGS-B seems to do the trick in other implementations:

```
import numpy as np
from scipy.optimize import minimize, Bounds

def quad(x):
    return x[0] ** 2 + x[1] ** 2

def quad_der(x):
    return 2 * (x[0] + x[1])

bounds = Bounds([1.0, 1.0], [2.0, 2.0])

x0 = np.array([1.5, 1.5])
res = minimize(quad, x0, method='L-BFGS-B', options={'disp': True}, bounds=bounds)

res.x
```
=> `array([1., 1.])`

**Comment by tmct** [comment]
I believe this is not a regression - all versions I've tried back to 3.20.0 exhibit this.

I guess it's not clear from the docs whether `FindMinimum` has a contract to remain feasible on intermediate steps, but the paper claims it should.

What I'm seeing in practice is:
```
(1.5, 1.5)
(1.0, 1.0)
(NaN, NaN)
(NaN, NaN)
(NaN, NaN)
...
MaximumIterationsException
```

This feels a bit wrong. I may take a closer look.

**Comment by cdrnet** [comment]
Thanks for the analysis and the fix - merged!
