### ISSUE TITLE
Failures of MathNet.Numerics.Tests.MKL

### ISSUE THREAD

**Issue by diluculo** [mathnet/mathnet-numerics#690]
I have tested `MathNet.Numerics.Tests.MKL` project with `MathNet.Numerics.MKL.Win` (v2.3.0, MKL 2018.0 R1). 

```
Math.NET Numerics Configuration:
Version 4.9.0
Built for .Net Framework 4.6.1
Linear Algebra Provider: Intel MKL (x64; revision 12; MKL 2018.0 Update 1)
Fourier Transform Provider: Intel MKL (x64; revision 12; MKL 2018.0 Update 1)
Max Degree of Parallelism: 8
Parallelize Elements: 300
Parallelize Order: 64
Check Distribution Parameters: True
Thread-Safe RNGs: True
Operating System: Microsoft Windows NT 6.2.9200.0
Framework: 4.0.30319.42000
```

There are 43 failed tests and 2 errors. Most of them may be minor and related to accuracy : 

```
1) Failed : MathNet.Numerics.UnitTests.DistributionTests.Multivariate.MatrixNormalTests.ValidateDensity
Not equal within 16 places. Expected:0.000156829273664912; Actual:0.000156829273664912
   위치: MathNet.Numerics.UnitTests.AssertHelpers.AlmostEqualRelative(Double expected, Double actual, Int32 decimalPlaces)

7) Failed : MathNet.Numerics.UnitTests.LinearAlgebraTests.Complex.Factorization.UserCholeskyTests.CanFactorizeRandomMatrix(1)
  Expected: (0.353088257803903, 0)
  But was:  (0.353088257803903, -8.01291052930066E-21)
   위치: MathNet.Numerics.UnitTests.LinearAlgebraTests.Complex.Factorization.UserCholeskyTests.CanFactorizeRandomMatrix(Int32 order)
```
And some are related with `LUFactor()` ( => [`LAPACKE_dgetrf`](https://software.intel.com/en-us/mkl-developer-reference-c-getrf) function of Intel MKL):

```
40) Error : MathNet.Numerics.UnitTests.RootFindingTests.BroydenTest.Seveneq3b
MathNet.Numerics.InvalidParameterException : An invalid parameter was passed to a native method, parameter number : 4
   위치: MathNet.Numerics.Providers.LinearAlgebra.Mkl.MklLinearAlgebraProvider.LUFactor(Double[] data, Int32 order, Int32[] ipiv)
   위치: MathNet.Numerics.LinearAlgebra.Double.Factorization.DenseLU.Create(DenseMatrix matrix)
   위치: MathNet.Numerics.RootFinding.Broyden.TryFindRootWithJacobianStep(Func`2 f, Double[] initialGuess, Double accuracy, Int32 maxIterations, Double jacobianStepSize, Double[]& root)
   위치: MathNet.Numerics.UnitTests.RootFindingTests.BroydenTest.Seveneq3b()
```

Am I missing something? `MKL 2019 R5` gives the same result, as well.

**Comment by cdrnet** [comment]
Yes, this has been bothering me for a while as well. I finally had some time to look into it, and noticed the following:

- Differences between different CPUs, e.g. Skylake vs Sandy Bridge. This was reduced by explicitly setting in the tests the MKL consistency level to `AVX`.
- Differences in NaN handling between managed and MKL, e.g. when unbounded root finding algorithms move outside of the supported domain of the function. The behavior is slightly more consistent now (they at least result in the same exception).
- Minor accuracy differences between managed and MKL, which could have all kind of reasons.

On the two machines I've tried, one of them with Intel Parallel Studio 2020.1, the other only with Intel MKL 2020.1, all the tests now pass. On a clean checkout, I've started the tests with `./build.sh mkltest` ([see also](https://numerics.mathdotnet.com/Build.html#Intel-MKL-on-Windows)) without any other changes or steps. I wonder whether they now pass on your environment as well?

**Comment by diluculo** [comment]
With MKL 2019.0 U5 on Coffee Lake(i7-9700KF), all the tests pass, but MKL 2018.0 U1 failed only at  

```
MathNet.Numerics.UnitTests.LinearAlgebraTests.Double.Factorization.EvdTests.CanFactorizeRandomSquareMatrix(50)
Not equal within 8 relative places. Expected:1.3356091897454E-06; Actual:1.33560918183506E-06
```

Now, I am not sure why I can't build the MKL project. I got the following errors:

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Start          00:00:00.0001280
Clean          00:00:00.4952310
ApplyVersion   00:00:00.0302953
Prepare        00:00:00.0000304
MklWinBuild    Failure
Total:         00:00:12.4002579
---------------------------------------------------------------------
Status:        Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Building D:\Codes\mathnet-numerics\MathNet.Numerics.MKL.sln failed with exitcode 1.
  2) : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.
  3) : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(126,5): The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.
  4) : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. 3) : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(126,5): The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.
  4) : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.
---------------------------------------------------------------------
```

.NET Core SDK 3.1.101, VS2017, and MKL 2019 U5 were installed.

**Comment by cdrnet** [comment]
Thanks for testing!

Weird - in case you still have the build output, at the beginning you should see a print-out of dotnet info - does it indeed state `Version: 3.1.101`?

**Comment by diluculo** [comment]
`build.cmd build` on the latest master works well.

The build output of `MklWinBuild` on the master is here: 
[MklWinBuild.txt](https://github.com/mathnet/mathnet-numerics/files/4564077/MklWinBuild.txt)

There is a warning `NU1503` for `dotnet restore MathNet.Numerics.MKL.sln`. Is it problematic?

```
Starting Target: MklWinBuild (==> Prepare)
dotnet restore MathNet.Numerics.MKL.sln --verbosity minimal /p:StrongName="False" /nr:false
D:\Codes\mathnet-numerics\src\NativeProviders\Windows\MKL\MKLWrapper.vcxproj : warning NU1503: Skipping restore for project 'D:\Codes\mathnet-numerics\src\NativeProviders\Windows\MKL\MKLWrapper.vcxproj'. The project file may be invalid or missing targets required for restore. [D:\Codes\mathnet-numerics\MathNet.Numerics.MKL.sln]
```

The corresponding lines on my working `directSparseSolver` branch(#695) is 

```
Starting Target: MklWinBuild (==> Prepare)
Building project: MathNet.Numerics.MKL.sln
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe  MathNet.Numerics.MKL.sln /t:Restore /m /nologo /nodeReuse:False  /v:m  /p:RestorePackages="False" /p:Configuration="Release" /p:StrongName="False" /logger:Fake.MsBuildLogger+ErrorLogger,"D:\Codes\mathnet-numerics\packages\build\FAKE\tools\FakeLib.dll"
```

By the way, I uninstalled VS2019 in January.

**Comment by diluculo** [comment]
@cdrnet, are you using VS2019? If yes, I will check whether VS2019 fixes the errors.

**Comment by cdrnet** [comment]
I use Rider primarily, but have both VS2017 and VS2019 installed on all machines I user for development. Opening, building and testing the MKL solution works for me in both VS2017 and VS2019. The solution still uses the VS2017 C++ platform toolset (v141).

That does not necessarily imply that it would also work in VS2017 if VS2019 is not installed.

Just to rule this out: if you open the Visual Studio installer, it does not report a warning that the installation is not complete? I've had similar errors in the past when one of the updates failed to complete.

Warning NU1503 I have as well on my machine, seems to be fine (it does not need to restore anything).

**Comment by cdrnet** [comment]
I've just realized what might be the issue: for MKL we still build directly with MsBuild, not with the .NET SDK tools (the main build uses the .NET Core SDK). VS2017 does not directly/officially support .NET Core 3. I suspect it might still work on my machine because the MsBuild coming with VS2019 does indeed support .NET Core 3. My VS2017 might effectively build using the MsBuild from VS2019. So it seems to me technically we do indeed no longer fully support VS2017.

Maybe it could also work to use `dotnet msbuild` instead of `MsBuild`, need to check. I'd expect VC++ to be stripped out there though.

**Comment by diluculo** [comment]
In VS2019, the `Intel Performance Libraries` section was not shown in the property pages of the MKL project, but it was listed in VS2017. There may be something wrong configuration in my PC.

When I changed the platform toolset from v141 to v142, `build.cmd mkltest` passed successfully.

**Comment by cdrnet** [comment]
It seems v142 is working well for me as well in VS2019. I've pushed it to master. So it seems we can finally resolve this issue? Thanks again!
