### ISSUE TITLE
VS 2019 can't open project files from sln

### ISSUE THREAD

**Issue by RyanGrange** [mathnet/mathnet-numerics#698]
The global.json file specifies latestPatch as the allowed roll forward instead of latestFeature, so anyone installed DNCore SDK 3.1 in the past week and getting 3.1.201 instead of the specified 3.1.101 can't open the projects.

**Comment by RyanGrange** [comment]
https://github.com/mathnet/mathnet-numerics/pull/699 created to allow SDK 3.1.x instead of 3.1.101.x.

**Comment by cdrnet** [comment]
It seems the 3.1.1 SDK got uninstalled? If I remember correctly, the Visual Studio updater sometimes uninstalls SDKs if, and only if, they were originally installed by the updater. But VS works perfectly well with the 3.1.1 SDK if installed. I've added a [note to the build instructions](https://numerics.mathdotnet.com/Build.html#System-Requirements) that the SDK is required. Thanks for the heads up.

**Comment by RyanGrange** [comment]
I see what happened.  Anyone downloading VS 2019 now like I did just to work on this is getting 16.5 which included 3.1.3 / 3.1.201. (Why can't they just pick a version number?)

I'll download 3.1.101, but it compiled fine on 3.1.201 as well in case you do decide not to lock it 3.1.101.x in the future.

**Comment by cdrnet** [comment]
We're quite restrictive currently because we've been affected by Microsoft breaking stuff in feature updates in the past. But maybe setting `rollForward` to `feature` (instead of the current `latestPatch` and the proposed `latestFeature`) would be a good compromise - we would still normally build on 3.1.1, also on CI, but it would not have broken you if I understand it correctly.

**Comment by cdrnet** [comment]
I've just pushed this to master. Thanks anyway for the PR!

**Comment by RyanGrange** [comment]
Been bitten by the occasionally broken updated library as well.  I did install 3.1.101 on my machine and all the projects were then able to open just fine under 2019 16.5.
