### ISSUE TITLE
Unused parameter in ValidateMaximum on RayleighTests.cs

### ISSUE THREAD

**Issue by Evangelink** [mathnet/mathnet-numerics#708]
The parameter `scale` is unused in method `ValidateMaximum` in `RayleigthTests.cs`: https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics.Tests/DistributionTests/Continuous/RayleighTests.cs#L197-L205

**Comment by cdrnet** [comment]
Good catch, thanks!
