### ISSUE TITLE
Unused parameter in test ValidateProbabilityLn

### ISSUE THREAD

**Issue by Evangelink** [mathnet/mathnet-numerics#709]
The parameter `pln` is unused in test `ValidateProbabilityLn` in `GeometricTests.cs`: https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics.Tests/DistributionTests/Discrete/GeometricTests.cs#L177-L200

I am not sure if it should replace the left parameter on line 195 or line 199.

**Comment by cdrnet** [comment]
The variant you chose in the PR makes sense to me - thanks!
