### ISSUE TITLE
openblas support

### ISSUE THREAD

**Issue by ahadrt** [mathnet/mathnet-numerics#722]
## Where is openblas

why openblas is not supported? we have used it in some projects. but the page is blank and not available document.

**Comment by cdrnet** [comment]
We still have a supported native linear algebra provider using OpenBLAS.

Which page is blank?

**Comment by ahadrt** [comment]
## That is good news, still support openblas 
I saw t[this page](https://numerics.mathdotnet.com/ReleaseNotes-OpenBLAS.html) -- that just has been written  initial version -- versus mkl  page which is full versions , while openblas have several versions after initial version ([the last version](https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.10))

**thank you for answering and so your nice library**
