### ISSUE TITLE
3 degree equation solver？

### ISSUE THREAD

**Issue by birdol** [mathnet/mathnet-numerics#723]
hi  there，
I Have an equation format like this:
X = C1 +C2 · (tS) + C3 · tD +C4 · (tS^2) + C5 · (tS·tD) + C6 · (tD^2) + C7 · (tS^3) + C8 · (tD·tS^2) +C9 · (tS·tD^2) + C10 · (tD^3) 

C1~C10 mean  ten coefficients
Ts and Td is input  ，X is the anwser。

this equation is from AHRI  Standard 540，for compressor model。

I donot konw what shall I do  in C#，to get the C1~C10？

**Comment by diluculo** [comment]
If your data set is given as { tS[i], tD[i], X[i] } where i = 1 .. n, the equation can be expressed as a matrix equation of the form Ax = b. Please refer to https://numerics.mathdotnet.com/Matrix.html and https://numerics.mathdotnet.com/LinearEquations.html.

**Comment by birdol** [comment]
thank you very much， i got it.
