### ISSUE TITLE
How to set Optimization parameters  like optimset in matlab for NelderMeadSimplex 

### ISSUE THREAD

**Issue by ximenchuigao** [mathnet/mathnet-numerics#734]
NelderMeadSimplex called fminsearch() in matlab. For fminsearch in we can set MaxFunEvals, MaxIter, TolFun, TolX and so on. But NelderMeadSimplex only has two paramters ConvergenceTolerance and MaximumIterations. As my understanding, the MaximumIterations is corresponding to MaxIter and ConvergenceTolerance is the same as TolFun. 
So how to set  MaxFunEvals, TolX in NelderMeadSimplex?

**Comment by eriove** [comment]
I'm afraid those aren't exposed (and some of them might not exist in the implementation either). I would suggest that you make a pull requests adding the properties you need. 

Another thing to be aware of is that is seems like Matlab is using a modified NMS which is less likely to get stuck in local minimums than the implementation here. But it might also be that I was lucky when I worked in Matlab and less so when I use it with MathNet Numerics (I no longer have access to the exact objective functions that worked well in Matlab).

(I was one of the people who took part in adding minimization to Mathnet Numerics but I'm not a maintainer)

**Comment by ximenchuigao** [comment]
Thank you @eriove for your detail reply.
