### ISSUE TITLE
Is it possible to solve generalized eigenvalue problems using MathNet.Numerics?

### ISSUE THREAD

**Issue by EmilPoulsen** [mathnet/mathnet-numerics#754]
Hi. Many thanks for this great library.

I was wondering if there is a way to compute the generalized eigenvalue problem with MathNet.Numerics of the form: 
```
| K − λM |= 0
```
where both K and M are symmetrical matrices. A common use case for this is computing natural frequencies of structures in structural dynamics, where K and M represent the stiffness and mass matrices.

The [MATLAB equivalent](https://www.mathworks.com/help/matlab/ref/eig.html#d122e338322) of this is:

```
[V,D] = eig(a,b)
```

Any input would be greatly appreciated. Thanks

**Comment by wo80** [comment]
If M is positive definite, you can use the Cholesky factorization to solve the generalized problem like done [here](https://github.com/wo80/mathnet-extensions/blob/master/src/Numerics/LinearAlgebra/Double/DenseMatrixExtensions.cs#L10).

**Comment by EmilPoulsen** [comment]
thanks @wo80! that should work
