### ISSUE TITLE
Support for .NET 5.0?

### ISSUE THREAD

**Issue by cgtyoder** [mathnet/mathnet-numerics#766]
Any plans for support for .NET 5.0? We are upgrading our code from .NET Framework to .NET 5, and can't complete it until this package supports it.

**Comment by eriove** [comment]
Since it supports .NET Standard it is completely compatible with .NET 5. We've been using it for a couple of months without problems.

**Comment by cdrnet** [comment]
Yes, via .NET Standard 2.0 all v4 releases already support .NET 5. Upcoming v5 which is currently being prepared on master will also add a build directly compiled against .NET 5 (but drops .NET Standard 1.*).

**Comment by cgtyoder** [comment]
My mistake - I believe I initially configured my .csproj file incorrectly. When I do it now, it is working. Thanks for the quick response.
