### ISSUE TITLE
System.Text.Json cannot deserialize Polynomial coefficients correctly

### ISSUE THREAD

**Issue by jetersen** [mathnet/mathnet-numerics#771]
Since the coefficients have a private setter than System.Text.Json cannot correctly deserialize the object.

Either the setter can be made public or add JsonInclude attribute.

Would you be open to include support for this in NET5?

```csharp
#if NET5_0_OR_GREATER
using System.Text.Json.Serialization;
#endif

namespace MathNet.Numerics
{

    public class Polynomial : IFormattable, IEquatable<Polynomial>, ICloneable
    {
        /// <summary>
        /// The coefficients of the polynomial in a
        /// </summary>
        [DataMember(Order = 1)]
#if NET5_0_OR_GREATER
        [JsonInclude]
#endif
        public double[] Coefficients { get; private set; }
```

I can submit a PR if you agree with the solution :)

**Comment by cdrnet** [comment]
Yes, that looks fine to me, thanks.

I suspect we may have the same problem also in a few other places.

**Comment by jetersen** [comment]
I can look through and find them :)

**Comment by jetersen** [comment]
FYI `JsonInclude` was only added in NET5.0 and `System.Text.Json` is only available in NET Standard and NET Framework as a NuGet package.

Not sure it is worth adding a NuGet package to include support for it in older runtimes.

**Comment by cdrnet** [comment]
No, it's fine to do this only with net5.0 and newer. Being able to do that was one of the main reasons of adding a proper net5.0 build in the first place (instead of just relying on netstandard2.0).

**Comment by jetersen** [comment]
Actually looking through the code, there is not that many places it makes sense to add. I basically found one in `DescriptiveStatistics` 😅

Currently vector and matrix cannot be (de)serialized as they are abstract and properly easier to (de)serialize as array/list and cast into a vector or matrix.

`Palf` being a mix of public and private fields is not something System.Text.Json can serialize.

**Comment by cdrnet** [comment]
I thought the concrete vector and matrix storage types were serializable - in practice that's not very usable/helpful though I guess.

**Comment by jetersen** [comment]
I can try again to see what needs to be done to make it serializable for `System.Text.Json`

**Comment by jetersen** [comment]
DenseVectorStorage is easy though that is relative, not so much the SparseVectorStorage.

But to make DenseVectorStorage You have to do something like this

```csharp
        [DataMember(Order = 1)]
#if NET5_0_OR_GREATER
        public T[] Data { get; init; }
#else
        public readonly T[] Data;
#endif

...

#if NET5_0_OR_GREATER
        [JsonConstructor]
        public DenseVectorStorage(T[] data) : base(data.Length)
        {
            Data = data;
        }
#endif
```
