### ISSUE TITLE
RobustNewtonRaphson f == 0.0 f / df = 0 / 0 bug

### ISSUE THREAD

**Issue by AnthonyLloyd** [mathnet/mathnet-numerics#774]
I think this class has the same bug I've seen in Numeric Recipies in that it needs to check f == 0.0 after an eval and return else you can get the condition that dx is set to NaN  when f / df is 0 / 0 for some functions. This then always exceeds the max interations.

**Comment by cdrnet** [comment]
Indeed - thanks! This should be addressed now.

**Comment by AnthonyLloyd** [comment]
Cool thanks
