### ISSUE TITLE
Use runtimes/native folder instead of NativeProvider.targets for NativeProvider Nuget packages

### ISSUE THREAD

**Issue by TillAlex** [mathnet/mathnet-numerics#872]
I have a solution referencing MathNet.Numerics.MKL.Win-x64 in a project which is referenced from many other library projects. During build the binary is copied to all the output folders leading to a total of 8 GB being used by 54 copies of the binary in my case.

MathNet.Numerics itself is not copied to all those output folders because it is correctly handled in the .deps.json files. Only the application itself has the libary in the output folder. This is different for the MKL binary. I assume this is because it is copied by the NativeProvider.targets.

I have other Nuget packages including native libraries in my project which do not have this issue. They do not use a target for copying. Instead they use the runtimes/.../native path in the nuget packages. Those libraries are only copied to the application folder, but not to the library project output folders. Here is a snippet of the corresponding project file:

`<ItemGroup>
        <None Update="runtimes/linux-arm64/native/Foo.so" Pack="true" PackagePath="" />
    </ItemGroup>`

My current workaround is to only reference the MathNet.Numerics.MKL.Win-x64 Nuget package from the application project, but this is error prone, because I tend to forget it when referencing the library from other applications.

Is it possible to change the behaviour of the NativeProvider nuget packages to be correctly handled by the .deps.json files?

**Comment by cdrnet** [comment]
Yes, this is actually something I wanted to do also for a while. I'm anyway changing a bit how native providers work and are packaged in v5.

**Comment by cdrnet** [comment]
The new beta packages now use runtimes/native folders. They still have a targets file for .NET Framework where the new structure doesn't work, but they should not interfere on .NET 6.

**Comment by cdrnet** [comment]
On .NET Framework maybe there could be some more tweaking for build vs buildTransitive - right now they are exactly the same.

**Comment by cdrnet** [comment]
Closing this for now as done - we can reopen if something comes up. Thanks again.
