### ISSUE TITLE
Having an issue with .Solve()

### ISSUE THREAD

**Issue by RejectKid** [mathnet/mathnet-numerics#889]
I currently have python code running [np.linalg.lstsq](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html) on a 20x20 array and a 20x1 array and i receive results.  however if i run the same arrays through .Solve() method i get NaNs.  What's happening here? I also am a little newer to this type of math, sorry in advanced.
![Untitled](https://user-images.githubusercontent.com/6117898/146812003-cd99c165-2b0f-4fc7-98ca-9f653cceef2a.png)

**Comment by jkalias** [comment]
Could you post the code sample?

**Comment by RejectKid** [comment]
I believe i figured it out.  It looks like .Solve() in .NET land is strict wheras its not in python.  there's no solution for the above.  but python then does least squares to do an estimated solve.

Thanks!

**Comment by jkalias** [comment]
Would you mind closing the issue, since this is resolved?
